import type { Request, Response } from "express";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { createMcpExpressApp } from "@modelcontextprotocol/sdk/server/express.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import * as z from "zod/v4";
import {
  calculateClinicalToolForAgent,
  getClinicalToolForAgent,
  searchClinicalToolsForAgent
} from "@peds-core/core";
import {
  createBearerAuthMiddleware,
  loadAuthConfig,
  protectedResourceMetadata,
  validateAuthConfig
} from "./auth.js";
import type { AuthConfig } from "./auth.js";
import { callSimulationBridge } from "./sim-client.js";
import { judgeDemoHtml } from "./judge-demo.js";
import {
  createStoreCarousel,
  createStoreIcon,
  privacyPolicyHtml,
  termsOfUseHtml
} from "./store-assets.js";

const jsonResult = (value: unknown) => ({
  content: [
    {
      type: "text" as const,
      text: JSON.stringify(value, null, 2)
    }
  ],
  structuredContent: value as Record<string, unknown>
});

export const createPedsCoreMcpServer = (): McpServer => {
  const server = new McpServer({
    name: "pedscore-ai",
    version: "0.1.0"
  });

  server.registerTool(
    "search_clinical_tools",
    {
      title: "Search pediatric clinical tools",
      description:
        "Find relevant PedsCore pediatric clinical tools from a clinical concept, problem, setting, specialty, or natural-language phrase. This is a discovery tool and does not itself provide a diagnosis.",
      inputSchema: {
        query: z.string().min(1).describe("Clinical concept or natural-language search query"),
        language: z.enum(["en", "es"]).default("en"),
        limit: z.number().int().min(1).max(20).default(5),
        activeOnly: z.boolean().default(true),
        calculableOnly: z.boolean().default(false)
      }
    },
    async ({ query, language, limit, activeOnly, calculableOnly }) => {
      const tools = searchClinicalToolsForAgent({
        query,
        language,
        limit,
        activeOnly,
        calculableOnly
      });

      return jsonResult({ tools });
    }
  );

  server.registerTool(
    "get_clinical_tool",
    {
      title: "Get pediatric clinical tool",
      description:
        "Return structured PedsCore metadata, required inputs, evidence references, and safety metadata for a clinical tool. Use this before calculation when the required inputs are not already known.",
      inputSchema: {
        slugOrId: z.string().min(1).describe("PedsCore tool slug or identifier"),
        language: z.enum(["en", "es"]).default("en")
      }
    },
    async ({ slugOrId, language }) => {
      const tool = getClinicalToolForAgent(slugOrId, language);

      if (!tool) {
        return {
          content: [{ type: "text", text: `Clinical tool not found: ${slugOrId}` }],
          isError: true
        };
      }

      return jsonResult({ tool });
    }
  );

  server.registerTool(
    "calculate_clinical_score",
    {
      title: "Calculate pediatric clinical score",
      description:
        "Execute an existing deterministic PedsCore calculator. The calculation is performed by PedsCore clinical logic, not generated by the language model. Call get_clinical_tool first if input identifiers or allowed values are unknown.",
      inputSchema: {
        toolId: z.string().min(1).describe("PedsCore calculator tool identifier"),
        input: z.record(z.string(), z.unknown()).describe("Input values keyed by the tool's PedsCore input identifiers")
      }
    },
    async ({ toolId, input }) => {
      const result = calculateClinicalToolForAgent(toolId, input);
      const failed = result.warnings.some((warning) =>
        ["calculator_not_implemented", "missing_required_inputs", "invalid_score_input"].includes(
          warning.id
        )
      );

      return {
        ...jsonResult({ result }),
        ...(failed ? { isError: true } : {})
      };
    }
  );


  server.registerTool(
    "start_simulation_case",
    {
      title: "Start pediatric MCI triage simulation",
      description:
        "Start a built-in synthetic pediatric mass-casualty triage scenario in SIM IMV. The simulator supplies the scenario and visible patient information; no real patient data is accepted.",
      inputSchema: {
        scenarioId: z.string().min(1).optional(),
        algorithmId: z.enum(["jumpstart", "salt", "ptt", "mitt"])
      }
    },
    async ({ scenarioId, algorithmId }) => {
      try {
        const result = await callSimulationBridge({
          action: "start_simulation_case",
          ...(scenarioId ? { scenarioId } : {}),
          algorithmId
        });
        return jsonResult({ result });
      } catch (error) {
        const message = error instanceof Error ? error.message : "simulation_bridge_error";
        return {
          content: [{ type: "text", text: `SIM IMV unavailable: ${message}` }],
          isError: true
        };
      }
    }
  );

  server.registerTool(
    "get_patient_findings",
    {
      title: "Get synthetic simulation patient findings",
      description:
        "Return the visible findings and valid initial assessment actions for one synthetic SIM IMV patient. This is educational simulation content, not a real-patient assessment service.",
      inputSchema: {
        scenarioId: z.string().min(1),
        algorithmId: z.enum(["jumpstart", "salt", "ptt", "mitt"]),
        patientId: z.string().min(1)
      }
    },
    async ({ scenarioId, algorithmId, patientId }) => {
      try {
        const result = await callSimulationBridge({
          action: "get_patient_findings",
          scenarioId,
          algorithmId,
          patientId
        });
        return jsonResult({ result });
      } catch (error) {
        const message = error instanceof Error ? error.message : "simulation_bridge_error";
        return {
          content: [{ type: "text", text: `SIM IMV unavailable: ${message}` }],
          isError: true
        };
      }
    }
  );

  server.registerTool(
    "submit_triage_decision",
    {
      title: "Submit synthetic triage decision",
      description:
        "Submit a triage category for one synthetic SIM IMV patient. Correctness and educational feedback are computed by the simulator's deterministic triage engine, not inferred by the language model.",
      inputSchema: {
        scenarioId: z.string().min(1),
        algorithmId: z.enum(["jumpstart", "salt", "ptt", "mitt"]),
        patientId: z.string().min(1),
        category: z.enum(["GREEN", "YELLOW", "RED", "BLACK", "GREY"])
      }
    },
    async ({ scenarioId, algorithmId, patientId, category }) => {
      try {
        const result = await callSimulationBridge({
          action: "submit_triage_decision",
          scenarioId,
          algorithmId,
          patientId,
          category
        });
        return jsonResult({ result });
      } catch (error) {
        const message = error instanceof Error ? error.message : "simulation_bridge_error";
        return {
          content: [{ type: "text", text: `SIM IMV unavailable: ${message}` }],
          isError: true
        };
      }
    }
  );

  return server;
};

export const createPedsCoreMcpApp = (options?: { authConfig?: AuthConfig }) => {
  const app = createMcpExpressApp({ host: "0.0.0.0" });
  const authConfig = options?.authConfig ?? loadAuthConfig();
  validateAuthConfig(authConfig);
  const authMiddleware = createBearerAuthMiddleware(authConfig);

  app.get("/health", (_req: Request, res: Response) => {
    res.status(200).json({
      status: "ok",
      service: "pedscore-ai-mcp",
      transport: "streamable-http",
      authentication: authConfig.mode
    });
  });

  app.get("/judge-demo", (_req: Request, res: Response) => {
    res
      .status(200)
      .type("html")
      .set("cache-control", "no-store")
      .send(judgeDemoHtml);
  });

  app.get("/privacy", (_req: Request, res: Response) => {
    res.status(200).type("html").send(privacyPolicyHtml);
  });

  app.get("/terms", (_req: Request, res: Response) => {
    res.status(200).type("html").send(termsOfUseHtml);
  });

  app.get("/store-assets/icon-:size.png", (req: Request, res: Response) => {
    const sizeParam = req.params.size;
    if (typeof sizeParam !== "string") {
      res.status(404).json({ error: "asset_not_found" });
      return;
    }

    const match = /^(64|72|88|126|180|241)x(64|72|88|126|180|241)$/.exec(sizeParam);
    if (!match || match[1] !== match[2]) {
      res.status(404).json({ error: "asset_not_found" });
      return;
    }

    const size = Number(match[1]);
    const image = createStoreIcon(size);
    res
      .status(200)
      .set({
        "content-type": "image/png",
        "content-length": String(image.length),
        "cache-control": "public, max-age=86400"
      })
      .send(image);
  });

  app.get("/store-assets/carousel-1.png", (_req: Request, res: Response) => {
    const image = createStoreCarousel();
    res
      .status(200)
      .set({
        "content-type": "image/png",
        "content-length": String(image.length),
        "cache-control": "public, max-age=86400"
      })
      .send(image);
  });

  app.get("/.well-known/oauth-protected-resource", (_req: Request, res: Response) => {
    const metadata = protectedResourceMetadata(authConfig);
    if (!metadata) {
      res.status(404).json({ error: "authentication_not_configured" });
      return;
    }

    res.status(200).json(metadata);
  });

  app.post("/mcp", authMiddleware, async (req: Request, res: Response) => {
    const server = createPedsCoreMcpServer();
    const transport = new StreamableHTTPServerTransport({});

    try {
      await server.connect(transport);
      await transport.handleRequest(req, res, req.body);

      res.on("close", () => {
        void transport.close();
        void server.close();
      });
    } catch (error) {
      console.error("MCP request failed", error);

      if (!res.headersSent) {
        res.status(500).json({
          jsonrpc: "2.0",
          error: {
            code: -32603,
            message: "Internal server error"
          },
          id: null
        });
      }
    }
  });

  const methodNotAllowed = (_req: Request, res: Response) => {
    res.status(405).json({
      jsonrpc: "2.0",
      error: {
        code: -32000,
        message: "Method not allowed"
      },
      id: null
    });
  };

  app.get("/mcp", methodNotAllowed);
  app.delete("/mcp", methodNotAllowed);

  return app;
};
