import type { Request, Response } from "express";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { createMcpExpressApp } from "@modelcontextprotocol/sdk/server/express.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import * as z from "zod/v4";
import {
  calculateClinicalToolForAgent,
  getClinicalToolForAgent,
  searchClinicalToolsForAgent
} from "@peds-core/core";
import {
  createBearerAuthMiddleware,
  loadAuthConfig,
  protectedResourceMetadata,
  validateAuthConfig
} from "./auth.js";
import type { AuthConfig } from "./auth.js";

const jsonResult = (value: unknown) => ({
  content: [
    {
      type: "text" as const,
      text: JSON.stringify(value, null, 2)
    }
  ],
  structuredContent: value as Record<string, unknown>
});

export const createPedsCoreMcpServer = (): McpServer => {
  const server = new McpServer({
    name: "pedscore-ai",
    version: "0.1.0"
  });

  server.registerTool(
    "search_clinical_tools",
    {
      title: "Search pediatric clinical tools",
      description:
        "Find relevant PedsCore pediatric clinical tools from a clinical concept, problem, setting, specialty, or natural-language phrase. This is a discovery tool and does not itself provide a diagnosis.",
      inputSchema: {
        query: z.string().min(1).describe("Clinical concept or natural-language search query"),
        language: z.enum(["en", "es"]).default("en"),
        limit: z.number().int().min(1).max(20).default(5),
        activeOnly: z.boolean().default(true),
        calculableOnly: z.boolean().default(false)
      }
    },
    async ({ query, language, limit, activeOnly, calculableOnly }) => {
      const tools = searchClinicalToolsForAgent({
        query,
        language,
        limit,
        activeOnly,
        calculableOnly
      });

      return jsonResult({ tools });
    }
  );

  server.registerTool(
    "get_clinical_tool",
    {
      title: "Get pediatric clinical tool",
      description:
        "Return structured PedsCore metadata, required inputs, evidence references, and safety metadata for a clinical tool. Use this before calculation when the required inputs are not already known.",
      inputSchema: {
        slugOrId: z.string().min(1).describe("PedsCore tool slug or identifier"),
        language: z.enum(["en", "es"]).default("en")
      }
    },
    async ({ slugOrId, language }) => {
      const tool = getClinicalToolForAgent(slugOrId, language);

      if (!tool) {
        return {
          content: [{ type: "text", text: `Clinical tool not found: ${slugOrId}` }],
          isError: true
        };
      }

      return jsonResult({ tool });
    }
  );

  server.registerTool(
    "calculate_clinical_score",
    {
      title: "Calculate pediatric clinical score",
      description:
        "Execute an existing deterministic PedsCore calculator. The calculation is performed by PedsCore clinical logic, not generated by the language model. Call get_clinical_tool first if input identifiers or allowed values are unknown.",
      inputSchema: {
        toolId: z.string().min(1).describe("PedsCore calculator tool identifier"),
        input: z.record(z.string(), z.unknown()).describe("Input values keyed by the tool's PedsCore input identifiers")
      }
    },
    async ({ toolId, input }) => {
      const result = calculateClinicalToolForAgent(toolId, input);
      const failed = result.warnings.some((warning) =>
        ["calculator_not_implemented", "missing_required_inputs", "invalid_score_input"].includes(
          warning.id
        )
      );

      return {
        ...jsonResult({ result }),
        ...(failed ? { isError: true } : {})
      };
    }
  );

  return server;
};

export const createPedsCoreMcpApp = (options?: { authConfig?: AuthConfig }) => {
  const app = createMcpExpressApp();
  const authConfig = options?.authConfig ?? loadAuthConfig();
  validateAuthConfig(authConfig);
  const authMiddleware = createBearerAuthMiddleware(authConfig);

  app.get("/health", (_req: Request, res: Response) => {
    res.status(200).json({
      status: "ok",
      service: "pedscore-ai-mcp",
      transport: "streamable-http",
      authentication: authConfig.mode
    });
  });

  app.get("/.well-known/oauth-protected-resource", (_req: Request, res: Response) => {
    const metadata = protectedResourceMetadata(authConfig);
    if (!metadata) {
      res.status(404).json({ error: "authentication_not_configured" });
      return;
    }

    res.status(200).json(metadata);
  });

  app.post("/mcp", authMiddleware, async (req: Request, res: Response) => {
    const server = createPedsCoreMcpServer();
    const transport = new StreamableHTTPServerTransport({});

    try {
      await server.connect(transport);
      await transport.handleRequest(req, res, req.body);

      res.on("close", () => {
        void transport.close();
        void server.close();
      });
    } catch (error) {
      console.error("MCP request failed", error);

      if (!res.headersSent) {
        res.status(500).json({
          jsonrpc: "2.0",
          error: {
            code: -32603,
            message: "Internal server error"
          },
          id: null
        });
      }
    }
  });

  const methodNotAllowed = (_req: Request, res: Response) => {
    res.status(405).json({
      jsonrpc: "2.0",
      error: {
        code: -32000,
        message: "Method not allowed"
      },
      id: null
    });
  };

  app.get("/mcp", methodNotAllowed);
  app.delete("/mcp", methodNotAllowed);

  return app;
};
