export const judgeDemoHtml = \`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>PedsCore AI — MCP Judge Console</title>
<style>
:root{color-scheme:dark;--bg:#071018;--panel:rgba(17,33,45,.88);--panel2:rgba(25,48,63,.72);--text:#f4fbff;--muted:#9fc1d3;--accent:#63d7ff;--accent2:#79f2c0;--warn:#ffd37a;--line:rgba(159,193,211,.18)}
*{box-sizing:border-box}body{margin:0;min-height:100vh;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:radial-gradient(circle at 15% 0%,rgba(99,215,255,.17),transparent 34rem),radial-gradient(circle at 92% 8%,rgba(121,242,192,.1),transparent 28rem),linear-gradient(180deg,#08131d 0%,var(--bg) 100%);color:var(--text)}
main{width:min(1180px,calc(100% - 32px));margin:0 auto;padding:48px 0 72px}.eyebrow{display:inline-flex;gap:8px;align-items:center;padding:7px 11px;border:1px solid var(--line);border-radius:999px;color:var(--accent2);background:rgba(121,242,192,.06);font-size:12px;font-weight:800;letter-spacing:.08em;text-transform:uppercase}.dot{width:8px;height:8px;border-radius:50%;background:var(--accent2);box-shadow:0 0 18px rgba(121,242,192,.8)}
h1{margin:22px 0 14px;max-width:900px;font-size:clamp(38px,6vw,72px);line-height:.98;letter-spacing:-.055em}.lead{max-width:790px;color:var(--muted);font-size:clamp(17px,2vw,21px);line-height:1.6}.principle{display:inline-block;margin-top:20px;font-weight:800}
.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:18px;margin-top:38px}.card{grid-column:span 6;padding:22px;border:1px solid var(--line);border-radius:22px;background:linear-gradient(180deg,var(--panel),rgba(11,25,35,.84));box-shadow:0 24px 80px rgba(0,0,0,.34)}.wide{grid-column:span 12}.num{color:var(--accent);font-size:12px;font-weight:800;letter-spacing:.1em;text-transform:uppercase}h2{margin:8px 0;font-size:23px;letter-spacing:-.025em}.copy{color:var(--muted);line-height:1.55;min-height:48px}.prompt{margin:18px 0;padding:14px 16px;border-radius:14px;background:var(--panel2);color:#dff7ff;border:1px solid rgba(99,215,255,.14);font-size:14px;line-height:1.5}
button{width:100%;border:0;border-radius:13px;padding:13px 16px;background:linear-gradient(135deg,#8ce3ff,#79f2c0);color:#05202b;font-weight:850;font-size:14px;cursor:pointer}button:disabled{opacity:.55;cursor:wait}.result{margin-top:15px;min-height:72px;padding:14px;border-radius:14px;border:1px dashed var(--line);color:var(--muted);font-size:14px;line-height:1.55;overflow-wrap:anywhere}.result strong{color:var(--text)}.result.ok{border-style:solid;border-color:rgba(121,242,192,.26);background:rgba(121,242,192,.05)}.result.warn{border-style:solid;border-color:rgba(255,211,122,.3);background:rgba(255,211,122,.05)}
details{margin-top:12px;border-top:1px solid var(--line);padding-top:12px}summary{cursor:pointer;color:var(--muted);font-size:12px;font-weight:700}pre{white-space:pre-wrap;word-break:break-word;color:#bde9fb;font:11px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;max-height:280px;overflow:auto}.architecture{display:grid;grid-template-columns:1fr auto 1fr auto 1fr;gap:12px;align-items:center;margin-top:18px}.node{padding:15px;text-align:center;border-radius:14px;border:1px solid var(--line);background:var(--panel2);font-weight:750}.arrow{color:var(--accent);font-size:22px}footer{margin-top:34px;color:#789bac;font-size:12px;line-height:1.6}a{color:var(--accent)}
@media(max-width:780px){main{padding-top:28px}.card,.wide{grid-column:span 12}.architecture{grid-template-columns:1fr}.arrow{transform:rotate(90deg);text-align:center}}
</style>
</head>
<body>
<main>
<div class="eyebrow"><span class="dot"></span>Live self-hosted MCP</div>
<h1>PedsCore AI<br/>Judge Console</h1>
<p class="lead">A live browser surface for verifying the hackathon submission against the same public MCP server used by the integration. Every button below performs a real MCP tools/call request.</p>
<span class="principle">The model may orchestrate. PedsCore and SIM IMV own the clinical logic.</span>
<section class="grid">
<article class="card"><div class="num">01 · Discovery</div><h2>Find the right pediatric tool</h2><p class="copy">Natural-language-oriented discovery over the real PedsCore catalog.</p><div class="prompt">“Find a pediatric score for assessing croup severity.”</div><button data-demo="discovery">Run live MCP call</button><div class="result" id="result-discovery">Ready.</div><div id="trace-discovery"></div></article>
<article class="card"><div class="num">02 · Structured metadata</div><h2>Inspect Apgar inputs</h2><p class="copy">Input requirements and metadata come from PedsCore rather than being invented conversationally.</p><div class="prompt">“Show me the inputs needed for the Apgar score.”</div><button data-demo="metadata">Run live MCP call</button><div class="result" id="result-metadata">Ready.</div><div id="trace-metadata"></div></article>
<article class="card"><div class="num">03 · Deterministic calculation</div><h2>Calculate Apgar</h2><p class="copy">The MCP layer delegates arithmetic to the existing deterministic calculator registry.</p><div class="prompt">5 min · HR 2 · respiration 2 · tone 2 · reflex 2 · color 1</div><button data-demo="apgar">Run live MCP call</button><div class="result" id="result-apgar">Expected reproducible result: 9/10.</div><div id="trace-apgar"></div></article>
<article class="card"><div class="num">04 · SIM IMV</div><h2>Start a pediatric MCI simulation</h2><p class="copy">The MCP contract is live. When the SIM bridge is reachable, the same call starts the synthetic school-bus scenario using JumpSTART.</p><div class="prompt">“Start the school-bus pediatric mass-casualty scenario using JumpSTART.”</div><button data-demo="sim">Run live MCP call</button><div class="result" id="result-sim">The tool contract can be verified while the private SIM deployment is pending.</div><div id="trace-sim"></div></article>
<article class="card wide"><div class="num">Execution boundary</div><h2>Inspectable by design</h2><div class="architecture"><div class="node">Conversation / agent</div><div class="arrow">→</div><div class="node">MCP tools</div><div class="arrow">→</div><div class="node">Deterministic domain logic</div></div></article>
</section>
<footer>Educational and simulation use only. No identifiable patient data should be submitted.<br/>Public MCP: <a href="/health">service health</a> · <a href="/privacy">privacy</a> · <a href="/terms">terms</a></footer>
</main>
<script>
const calls={
discovery:{name:"search_clinical_tools",arguments:{query:"pediatric croup severity score",language:"en",limit:5,activeOnly:true,calculableOnly:false}},
metadata:{name:"get_clinical_tool",arguments:{slugOrId:"apgar",language:"en"}},
apgar:{name:"calculate_clinical_score",arguments:{toolId:"apgar",input:{assessment_time:"five_minutes",heart_rate:2,respiratory_effort:2,muscle_tone:2,reflex_irritability:2,color:1}}},
sim:{name:"start_simulation_case",arguments:{scenarioId:"school-bus",algorithmId:"jumpstart"}}
};
function parseRpc(text,ct){if(ct.includes("application/json"))return JSON.parse(text);const lines=text.split(/\\r?\\n/).filter(function(line){return line.startsWith("data:")});if(!lines.length)throw new Error("No JSON-RPC payload returned");return JSON.parse(lines[lines.length-1].slice(5).trim())}
async function toolCall(spec){const response=await fetch("/mcp",{method:"POST",headers:{"content-type":"application/json","accept":"application/json, text/event-stream"},body:JSON.stringify({jsonrpc:"2.0",id:Date.now(),method:"tools/call",params:spec})});const text=await response.text();const payload=parseRpc(text,response.headers.get("content-type")||"");if(!response.ok||payload.error)throw new Error(JSON.stringify(payload.error||payload));return payload}
function summary(kind,payload){const r=payload.result||{};const s=r.structuredContent||{};if(kind==="discovery"){const first=(s.tools||[])[0];return first?"Top catalog result: <strong>"+(first.name||first.title||first.id)+"</strong> ("+first.id+")":"No catalog result returned."}if(kind==="metadata"){const tool=s.tool;const count=tool&&tool.inputs?tool.inputs.length:"structured";return tool?"Loaded <strong>"+(tool.name||tool.title||tool.id)+"</strong>. Inputs: <strong>"+count+"</strong>.":"Tool metadata returned."}if(kind==="apgar"){const x=s.result;return x?"Deterministic PedsCore result: <strong>"+x.score+"/"+x.maxScore+"</strong> · tool <strong>"+x.toolId+"</strong>.":"Calculation response returned."}if(kind==="sim"){if(r.isError)return"SIM MCP contract is live; backend bridge is not configured on this deployment yet.";const x=s.result;return x&&x.scenario?"Started <strong>"+x.scenario.title+"</strong> with <strong>"+x.patientCount+"</strong> synthetic patients.":"SIM response returned."}return"MCP response returned."}
document.querySelectorAll("button[data-demo]").forEach(function(button){button.addEventListener("click",async function(){const kind=button.dataset.demo;const result=document.getElementById("result-"+kind);const trace=document.getElementById("trace-"+kind);button.disabled=true;result.className="result";result.textContent="Calling the live MCP server…";trace.innerHTML="";try{const payload=await toolCall(calls[kind]);result.innerHTML=summary(kind,payload);result.classList.add(payload.result&&payload.result.isError?"warn":"ok");const d=document.createElement("details");const s=document.createElement("summary");s.textContent="Show MCP trace";const p=document.createElement("pre");p.textContent=JSON.stringify(payload,null,2);d.appendChild(s);d.appendChild(p);trace.appendChild(d)}catch(error){result.textContent="Request failed: "+String(error);result.classList.add("warn")}finally{button.disabled=false}})});
</script>
</body>
</html>\`;
