import type {
  AgeGroupTag,
  CareSettingTag,
  ClinicalFunctionTag,
  ClinicalRiskTier,
  ClinicalSpecialty,
  ClinicalToolDiscoveryMetadata,
  ContentReuseStatus,
  DiscoveryExclusion,
  DiscoveryCalculationAvailability,
  ExactAgeApplicability,
  InputModality,
  InteractionMode,
  LongitudinalUse,
  SurfaceStatus
} from "../types.js";

type Seed = {
  surfaceStatus?: SurfaceStatus;
  specialties: ClinicalSpecialty[];
  problems: string[];
  ages: AgeGroupTag[];
  exactAgeApplicability?: ExactAgeApplicability;
  settings: CareSettingTag[];
  functions: ClinicalFunctionTag[];
  modes: InteractionMode[];
  longitudinal?: LongitudinalUse;
  inputs?: InputModality[];
  calc?: DiscoveryCalculationAvailability;
  reuse?: ContentReuseStatus;
  risk?: ClinicalRiskTier;
  es?: string[];
  en?: string[];
  exclusions?: DiscoveryExclusion[];
  compare?: string[];
  related?: string[];
};

const defaultSurfaceStatus = (
  calculationAvailability: DiscoveryCalculationAvailability
): SurfaceStatus => calculationAvailability === "local_planned" ? "draft" : "active";

const d = (seed: Seed): ClinicalToolDiscoveryMetadata => {
  const calculationAvailability = seed.calc ?? "local_planned";

  return {
  surfaceStatus: seed.surfaceStatus ?? defaultSurfaceStatus(calculationAvailability),
  specialties: seed.specialties,
  clinicalProblems: seed.problems,
  ageGroups: seed.ages,
  ...(seed.exactAgeApplicability ? { exactAgeApplicability: seed.exactAgeApplicability } : {}),
  careSettings: seed.settings,
  clinicalFunctions: seed.functions,
  interactionModes: seed.modes,
  longitudinalUse: seed.longitudinal ?? "possible",
  inputModalities: seed.inputs ?? ["clinical_observation"],
  calculationAvailability,
  reuseStatus: seed.reuse ?? "unresolved",
  clinicalRiskTier: seed.risk ?? "moderate",
  aliases: { es: seed.es ?? [], en: seed.en ?? [] },
  exclusions: seed.exclusions ?? [],
  comparisonGroupIds: seed.compare ?? [],
  relatedToolIds: seed.related ?? []
  };
};

const neo = ["neonatology"] as ClinicalSpecialty[];
const ed = ["emergency_medicine"] as ClinicalSpecialty[];
const picu = ["intensive_care"] as ClinicalSpecialty[];
const resp = ["respiratory"] as ClinicalSpecialty[];
const neuro = ["neurology"] as ClinicalSpecialty[];
const pain = ["pain_medicine"] as ClinicalSpecialty[];
const renal = ["nephrology"] as ClinicalSpecialty[];

const existingToolDiscoveryById: Record<string, ClinicalToolDiscoveryMetadata> = {
  apgar: d({ specialties: neo, problems:["newborn_transition"], ages:["term_newborn","neonate_0_28d"], settings:["delivery_room"], functions:["severity","reference_only"], modes:["calculator","reference_scale"], longitudinal:"supported", risk:"high", calc:"local_active", reuse:"open", es:["apgar","test de apgar"], en:["apgar","apgar score"] }),
  silverman_andersen: d({ specialties:[...neo,...resp], problems:["neonatal_respiratory_distress","respiratory_distress"], ages:["preterm","term_newborn","neonate_0_28d"], settings:["delivery_room","newborn_ward","nicu"], functions:["severity","longitudinal_monitoring"], modes:["calculator","reference_scale","longitudinal_monitoring"], longitudinal:"primary", calc:"local_active", reuse:"open", risk:"high", es:["silverman","silverman-andersen","dificultad respiratoria neonatal"], en:["silverman andersen","neonatal respiratory distress"], compare:["neonatal_respiratory_distress"] }),
  wood_downes_ferres: d({ specialties:resp, problems:["asthma","bronchospasm","respiratory_distress"], ages:["infant","toddler","preschool","school_age","adolescent"], settings:["emergency_department","inpatient_ward"], functions:["severity"], modes:["calculator","reference_scale"], calc:"local_active", reuse:"unresolved", risk:"high", es:["wood-downes-ferres","wood downes ferres"], en:["wood-downes-ferres"], compare:["acute_asthma_severity"] }),
  ballard: d({ specialties:[...neo,"growth_development"], problems:["gestational_age_assessment","maturity_assessment"], ages:["preterm","term_newborn","neonate_0_28d"], settings:["delivery_room","newborn_ward","nicu"], functions:["maturity_assessment","developmental_assessment"], modes:["calculator","reference_scale","visual_atlas"], longitudinal:"not_applicable", calc:"local_active", reuse:"unresolved", risk:"moderate", es:["ballard","new ballard","edad gestacional"], en:["new ballard score","gestational age assessment"], compare:["gestational_age_assessment"], related:["dubowitz"] }),
  dubowitz: d({ specialties:[...neo,"growth_development"], problems:["gestational_age_assessment","maturity_assessment"], ages:["preterm","term_newborn","neonate_0_28d"], settings:["newborn_ward","nicu"], functions:["maturity_assessment","developmental_assessment"], modes:["calculator","reference_scale"], longitudinal:"not_applicable", calc:"local_active", reuse:"unresolved", es:["dubowitz","madurez gestacional"], en:["dubowitz gestational assessment"], compare:["gestational_age_assessment"], related:["ballard"] }),
  sarnat: d({ specialties:[...neo,...neuro], problems:["neonatal_encephalopathy","hypoxic_ischemic_encephalopathy"], ages:["term_newborn","neonate_0_28d"], settings:["delivery_room","nicu"], functions:["staging","severity","longitudinal_monitoring"], modes:["longitudinal_staging","reference_scale"], longitudinal:"primary", calc:"not_applicable", reuse:"unresolved", risk:"critical", es:["sarnat","sarnat clasico","encefalopatia neonatal","ehi"], en:["sarnat","classic sarnat","neonatal encephalopathy","hie"], compare:["neonatal_encephalopathy"], related:["modified_sarnat_nichd","thompson_hie"] }),
  modified_sarnat_nichd: d({ specialties:[...neo,...neuro], problems:["neonatal_encephalopathy","hypoxic_ischemic_encephalopathy"], ages:["term_newborn","neonate_0_28d"], settings:["delivery_room","nicu"], functions:["staging","severity"], modes:["calculator","examination_framework","reference_scale"], longitudinal:"supported", calc:"local_active", reuse:"unresolved", risk:"critical", es:["modified sarnat","sarnat modificado","nichd","encefalopatia neonatal"], en:["modified sarnat","nichd sarnat","neonatal encephalopathy"], compare:["neonatal_encephalopathy"], related:["sarnat","thompson_hie"] }),
  thompson_hie: d({ specialties:[...neo,...neuro], problems:["neonatal_encephalopathy","hypoxic_ischemic_encephalopathy"], ages:["term_newborn","neonate_0_28d"], settings:["nicu"], functions:["severity","longitudinal_monitoring"], modes:["calculator","reference_scale","longitudinal_monitoring"], longitudinal:"primary", calc:"local_active", reuse:"unresolved", risk:"critical", es:["thompson","encefalopatia hipoxico isquemica"], en:["thompson hie score","neonatal encephalopathy"], compare:["neonatal_encephalopathy"], related:["sarnat","modified_sarnat_nichd"] }),
  eat_sleep_console: d({ specialties:neo, problems:["neonatal_withdrawal","neonatal_abstinence"], ages:["term_newborn","neonate_0_28d","infant"], settings:["newborn_ward","nicu"], functions:["functional_status","longitudinal_monitoring"], modes:["clinical_framework"], longitudinal:"primary", calc:"not_applicable", reuse:"open", risk:"high", es:["eat sleep console","comer dormir consolar"], en:["eat sleep console","esc"], compare:["neonatal_withdrawal"] }),
  nips: d({ specialties:[...neo,...pain], problems:["neonatal_pain","acute_pain","procedural_pain"], ages:["preterm","term_newborn","neonate_0_28d"], settings:["newborn_ward","nicu","postoperative"], functions:["pain_assessment"], modes:["calculator","reference_scale"], longitudinal:"supported", calc:"local_active", reuse:"open", risk:"moderate", es:["nips","dolor neonatal"], en:["nips","neonatal infant pain scale"], compare:["neonatal_pain"] }),
  pipp: d({ specialties:[...neo,...pain], problems:["neonatal_pain","procedural_pain"], ages:["preterm","term_newborn","neonate_0_28d"], settings:["nicu"], functions:["pain_assessment"], modes:["reference_scale"], longitudinal:"supported", calc:"blocked_by_rights", reuse:"unresolved", es:["pipp"], en:["premature infant pain profile"], compare:["neonatal_pain"] }),
  pipp_r: d({ specialties:[...neo,...pain], problems:["neonatal_pain","procedural_pain"], ages:["preterm","term_newborn","neonate_0_28d"], settings:["nicu"], functions:["pain_assessment"], modes:["reference_scale","licensed_external_tool"], longitudinal:"supported", calc:"blocked_by_rights", reuse:"permission_required", es:["pipp-r","dolor prematuro"], en:["pipp-r","premature infant pain profile revised"], compare:["neonatal_pain"] }),
  cries: d({ specialties:[...neo,...pain], problems:["neonatal_pain","postoperative_pain"], ages:["neonate_0_28d"], settings:["postoperative","nicu"], functions:["pain_assessment"], modes:["calculator","reference_scale"], longitudinal:"supported", calc:"local_active", reuse:"unresolved", risk:"moderate", es:["cries","dolor postoperatorio neonatal"], en:["cries neonatal pain"], compare:["neonatal_pain"] }),
  comfortneo: d({ specialties:[...neo,...pain,"sedation"], problems:["neonatal_pain","neonatal_sedation","distress"], ages:["preterm","term_newborn","neonate_0_28d"], settings:["nicu"], functions:["pain_assessment","sedation_assessment","longitudinal_monitoring"], modes:["reference_scale","longitudinal_monitoring"], longitudinal:"primary", calc:"blocked_by_rights", reuse:"unresolved", es:["comfortneo"], en:["comfortneo"], compare:["neonatal_pain","neonatal_sedation"] }),
  bhutani_nomogram: d({ specialties:[...neo,"gastroenterology"], problems:["hyperbilirubinemia","jaundice"], ages:["term_newborn","neonate_0_28d"], settings:["newborn_ward","outpatient_clinic"], functions:["risk_stratification","reference_only"], modes:["visual_atlas","reference_scale"], longitudinal:"possible", calc:"not_applicable", reuse:"permission_required", risk:"high", inputs:["laboratory"], es:["bhutani","nomograma bilirrubina","ictericia"], en:["bhutani nomogram","bilirubin nomogram"], compare:["neonatal_hyperbilirubinemia"] }),
  aap_2022_hyperbilirubinemia: d({ specialties:[...neo,"gastroenterology"], problems:["hyperbilirubinemia","jaundice"], ages:["preterm","term_newborn","neonate_0_28d"], exactAgeApplicability:{ minimumAgeDays:0, maximumAgeDaysExclusive:14.01 }, settings:["newborn_ward","nicu","outpatient_clinic"], functions:["risk_stratification","reference_only"], modes:["clinical_rule","licensed_external_tool"], longitudinal:"supported", calc:"external_official", reuse:"external_only", risk:"critical", inputs:["laboratory","history"], es:["aap 2022 bilirrubina","hiperbilirrubinemia neonatal","fototerapia","ictericia neonatal"], en:["aap 2022 bilirubin","neonatal hyperbilirubinemia","phototherapy threshold","newborn jaundice"], compare:["neonatal_hyperbilirubinemia"], related:["bhutani_nomogram"] }),
  neonatal_growth_fenton: d({ specialties:[...neo,"growth_development","nutrition"], problems:["preterm_growth","growth"], ages:["preterm","term_newborn"], settings:["nicu","outpatient_clinic"], functions:["growth_assessment","reference_only"], modes:["reference_scale","visual_atlas"], longitudinal:"supported", calc:"not_applicable", reuse:"external_only", risk:"moderate", inputs:["growth_measurements"], es:["fenton 2013","fenton legacy","crecimiento prematuro"], en:["fenton 2013","legacy fenton","preterm growth"], compare:["preterm_growth"], related:["fenton_2025_growth"] }),
  fenton_2025_growth: d({ specialties:[...neo,"growth_development","nutrition"], problems:["preterm_growth","growth"], ages:["preterm","term_newborn"], settings:["nicu","outpatient_clinic"], functions:["growth_assessment","longitudinal_monitoring"], modes:["licensed_external_tool","visual_atlas"], longitudinal:"primary", calc:"external_official", reuse:"external_only", risk:"moderate", inputs:["growth_measurements"], es:["fenton 2025","crecimiento prematuro","percentil prematuro","z score prematuro"], en:["fenton 2025","preterm growth","preterm percentile","preterm z score"], compare:["preterm_growth"], related:["neonatal_growth_fenton","who_growth_module"] }),
  brighton_pews: d({ specialties:[...ed,"general_pediatrics"], problems:["clinical_deterioration"], ages:["all_pediatric"], settings:["inpatient_ward"], functions:["risk_stratification","severity"], modes:["reference_scale"], calc:"blocked_by_rights", reuse:"unresolved", risk:"high", es:["brighton pews"], en:["brighton pews"], compare:["pediatric_early_warning"] }),
  bedside_pews: d({ specialties:[...ed,...picu,"general_pediatrics"], problems:["clinical_deterioration"], ages:["all_pediatric"], exactAgeApplicability:{ minimumAgeDays:0, maximumAgeDaysExclusive:6574.5 }, settings:["inpatient_ward"], functions:["risk_stratification","severity","longitudinal_monitoring"], modes:["calculator","reference_scale","longitudinal_monitoring"], longitudinal:"primary", calc:"local_active", reuse:"attribution_required", risk:"high", inputs:["vital_signs","clinical_observation"], es:["bedside pews","pews bedside","deterioro pediatrico"], en:["bedside pews","pediatric early warning","clinical deterioration"], compare:["pediatric_early_warning"] }),
  westley_croup: d({ specialties:[...resp,...ed], problems:["croup","upper_airway_obstruction"], ages:["infant","toddler","preschool","school_age"], settings:["emergency_department","primary_care","inpatient_ward"], functions:["severity"], modes:["calculator","reference_scale"], calc:"local_active", reuse:"open", risk:"high", es:["westley","crup","laringitis"], en:["westley croup","croup"], compare:["croup_severity"] }),
  modified_tal: d({ specialties:[...resp,...ed], problems:["bronchiolitis","wheezing","respiratory_distress"], ages:["infant","toddler"], settings:["emergency_department","primary_care","inpatient_ward"], functions:["severity","longitudinal_monitoring"], modes:["calculator","reference_scale"], longitudinal:"supported", calc:"local_planned", reuse:"open", risk:"high", inputs:["clinical_observation","vital_signs"], es:["tal","score tal","bronquiolitis","dificultad respiratoria"], en:["modified tal","tal score","bronchiolitis severity"], compare:["bronchiolitis_severity"], related:["rdai","brosjod"] }),
  taussig_croup: d({ specialties:[...resp,...ed], problems:["croup","upper_airway_obstruction"], ages:["infant","toddler","preschool","school_age"], settings:["emergency_department","primary_care","inpatient_ward"], functions:["severity","longitudinal_monitoring"], modes:["calculator","reference_scale"], longitudinal:"supported", calc:"local_planned", reuse:"open", risk:"high", inputs:["clinical_observation","physical_examination"], es:["taussig","laringitis","crup"], en:["taussig","croup score"], compare:["croup_severity"], related:["westley_croup"] }),
  pram: d({ specialties:[...resp,...ed], problems:["asthma","acute_asthma"], ages:["preschool","school_age","adolescent"], exactAgeApplicability:{ minimumAgeDays:730.5, maximumAgeDaysExclusive:6574.5 }, settings:["emergency_department","inpatient_ward"], functions:["severity","treatment_response"], modes:["calculator","reference_scale"], longitudinal:"supported", calc:"local_active", reuse:"open", risk:"high", inputs:["clinical_observation","vital_signs","physical_examination"], es:["pram","asma aguda","crisis asmatica","crisis de asma"], en:["pram","acute asthma"], compare:["acute_asthma_severity"], related:["pass"] }),
  rdai: d({ specialties:[...resp,...ed], problems:["bronchiolitis","wheezing"], ages:["infant","toddler"], settings:["emergency_department","inpatient_ward"], functions:["severity"], modes:["reference_scale"], calc:"blocked_by_rights", reuse:"unresolved", es:["rdai","bronquiolitis"], en:["rdai","respiratory distress assessment instrument"], compare:["bronchiolitis_severity"], related:["brosjod"] }),
  brosjod: d({ specialties:[...resp,...ed], problems:["bronchiolitis"], ages:["infant"], settings:["emergency_department","inpatient_ward"], functions:["severity","longitudinal_monitoring"], modes:["reference_scale","longitudinal_monitoring"], longitudinal:"supported", calc:"blocked_by_rights", reuse:"unresolved", es:["brosjod","bronquiolitis"], en:["brosjod bronchiolitis"], compare:["bronchiolitis_severity"], related:["rdai"] }),
  pass: d({ specialties:[...resp,...ed], problems:["asthma","acute_asthma"], ages:["toddler","preschool","school_age","adolescent"], settings:["emergency_department"], functions:["severity"], modes:["calculator","reference_scale"], calc:"local_planned", reuse:"open", risk:"high", inputs:["clinical_observation","physical_examination"], es:["pass","asma"], en:["pediatric asthma severity score","pass"], compare:["acute_asthma_severity"], related:["pram"] }),
  risc: d({ specialties:[...resp,"infectious_disease"], problems:["lower_respiratory_infection","pneumonia"], ages:["infant","toddler"], exactAgeApplicability:{ maximumAgeDaysExclusive:730.5 }, settings:["inpatient_ward"], functions:["mortality_risk","prognosis"], modes:["calculator"], calc:"local_planned", reuse:"public_domain", risk:"high", inputs:["vital_signs","clinical_observation","history","growth_measurements"], es:["risc","infeccion respiratoria"], en:["risc respiratory index of severity"], compare:["respiratory_mortality"] }),
  mrisc: d({ specialties:[...resp,"infectious_disease"], problems:["lower_respiratory_infection","pneumonia"], ages:["infant","toddler","preschool"], exactAgeApplicability:{ maximumAgeDaysExclusive:1826.25 }, settings:["inpatient_ward"], functions:["mortality_risk","prognosis"], modes:["calculator"], calc:"local_planned", reuse:"open", risk:"high", inputs:["history","clinical_observation","growth_measurements"], es:["mrisc"], en:["modified risc","mrisc"], compare:["respiratory_mortality"] }),
  pediatric_gcs: d({ specialties:[...neuro,...ed,...picu], problems:["coma","altered_consciousness","trauma"], ages:["all_pediatric"], settings:["emergency_department","picu","inpatient_ward"], functions:["severity","staging","longitudinal_monitoring"], modes:["reference_scale","licensed_external_tool"], longitudinal:"primary", calc:"external_official", reuse:"permission_required", risk:"critical", es:["glasgow pediatrico","gcs pediatrico"], en:["pediatric glasgow coma scale","pediatric gcs"], compare:["consciousness"] }),
  clinical_dehydration_scale: d({ specialties:[...ed,"gastroenterology"], problems:["dehydration","gastroenteritis"], ages:["infant","toddler","preschool"], settings:["emergency_department","primary_care"], functions:["severity","risk_stratification"], modes:["calculator","reference_scale"], calc:"local_active", reuse:"open", risk:"high", es:["cds","escala deshidratacion"], en:["clinical dehydration scale","dehydration"], compare:["pediatric_dehydration"], related:["gorelick_dehydration"] }),
  pediatric_appendicitis_score: d({ specialties:ed, problems:["appendicitis","abdominal_pain"], ages:["school_age","adolescent","age_defined_by_tool"], settings:["emergency_department"], functions:["risk_stratification","diagnostic_support"], modes:["calculator","clinical_rule"], calc:"local_active", reuse:"open", risk:"high", es:["pas","score apendicitis pediatrica"], en:["pediatric appendicitis score","pas"], compare:["appendicitis_risk"] }),
  gorelick_dehydration: d({ specialties:[...ed,"gastroenterology"], problems:["dehydration","gastroenteritis"], ages:["infant","toddler","preschool"], exactAgeApplicability:{ minimumAgeDays:30, maximumAgeDaysExclusive:1826.25 }, settings:["emergency_department"], functions:["severity","risk_stratification"], modes:["calculator","reference_scale"], calc:"local_planned", reuse:"open", risk:"high", inputs:["clinical_observation","physical_examination"], es:["gorelick","deshidratacion"], en:["gorelick dehydration"], compare:["pediatric_dehydration"], related:["clinical_dehydration_scale"] }),
  pediatric_burn_tbsa: d({ specialties:[...ed,"burns","trauma"], problems:["burns","tbsa"], ages:["all_pediatric"], settings:["emergency_department","prehospital","inpatient_ward"], functions:["severity","risk_stratification"], modes:["calculator","visual_atlas"], calc:"local_active", reuse:"open", risk:"critical", inputs:["physical_examination"], es:["lund browder","superficie corporal quemada","scq"], en:["pediatric tbsa","lund browder","burn surface area"], compare:["burn_assessment"] }),
  pecarn_tbi_under_2: d({ specialties:[...ed,"trauma"], problems:["traumatic_brain_injury","head_trauma"], ages:["infant","toddler"], exactAgeApplicability:{ maximumAgeDaysExclusive:730.5 }, settings:["emergency_department"], functions:["risk_stratification","diagnostic_support"], modes:["clinical_rule","calculator"], longitudinal:"not_applicable", calc:"local_active", reuse:"open", risk:"critical", es:["pecarn tce menor 2","tce lactante"], en:["pecarn tbi under 2","head injury"], compare:["pediatric_head_injury"], related:["pecarn_tbi_2_or_more","catch_tbi","chalice_tbi"] }),
  pecarn_tbi_2_or_more: d({ specialties:[...ed,"trauma"], problems:["traumatic_brain_injury","head_trauma"], ages:["toddler","preschool","school_age","adolescent"], exactAgeApplicability:{ minimumAgeDays:730.5 }, settings:["emergency_department"], functions:["risk_stratification","diagnostic_support"], modes:["clinical_rule","calculator"], longitudinal:"not_applicable", calc:"local_active", reuse:"open", risk:"critical", es:["pecarn tce mayor 2","tce"], en:["pecarn tbi 2 or more","head injury"], compare:["pediatric_head_injury"], related:["pecarn_tbi_under_2","catch_tbi","chalice_tbi"] }),
  catch_tbi: d({ specialties:[...ed,"trauma"], problems:["traumatic_brain_injury","head_trauma"], ages:["all_pediatric"], settings:["emergency_department"], functions:["risk_stratification","diagnostic_support"], modes:["clinical_rule","calculator"], longitudinal:"not_applicable", calc:"local_active", reuse:"open", risk:"critical", es:["catch","tce"], en:["catch head injury"], compare:["pediatric_head_injury"] }),
  chalice_tbi: d({ specialties:[...ed,"trauma"], problems:["traumatic_brain_injury","head_trauma"], ages:["all_pediatric"], settings:["emergency_department"], functions:["risk_stratification","diagnostic_support"], modes:["clinical_rule","calculator"], longitudinal:"not_applicable", calc:"local_active", reuse:"open", risk:"critical", es:["chalice","tce"], en:["chalice head injury"], compare:["pediatric_head_injury"] }),
  sipa: d({ specialties:[...ed,"trauma"], problems:["shock","trauma"], ages:["preschool","school_age","adolescent"], exactAgeApplicability:{ minimumAgeDays:1461, maximumAgeDaysExclusive:6209.25 }, settings:["emergency_department","prehospital"], functions:["risk_stratification","severity"], modes:["calculator"], longitudinal:"supported", calc:"local_active", reuse:"open", risk:"critical", inputs:["vital_signs"], es:["sipa","indice shock pediatrico"], en:["shock index pediatric adjusted","sipa"], compare:["pediatric_shock"] }),
  qtc_bazett: d({ specialties:["cardiology"], problems:["prolonged_qt","ecg"], ages:["all_pediatric"], settings:["emergency_department","outpatient_clinic","inpatient_ward"], functions:["diagnostic_support"], modes:["calculator"], calc:"local_active", reuse:"public_domain", inputs:["ecg"], es:["qtc bazett","qt corregido"], en:["bazett qtc"], compare:["qtc_formula"] }),
  qtc_fridericia: d({ specialties:["cardiology"], problems:["prolonged_qt","ecg"], ages:["all_pediatric"], settings:["emergency_department","outpatient_clinic","inpatient_ward"], functions:["diagnostic_support"], modes:["calculator"], calc:"local_active", reuse:"public_domain", inputs:["ecg"], es:["qtc fridericia"], en:["fridericia qtc"], compare:["qtc_formula"] }),
  qtc_framingham: d({ specialties:["cardiology"], problems:["prolonged_qt","ecg"], ages:["all_pediatric"], settings:["outpatient_clinic","inpatient_ward"], functions:["diagnostic_support","reference_only"], modes:["calculator"], calc:"local_active", reuse:"public_domain", inputs:["ecg"], es:["qtc framingham"], en:["framingham qtc"], compare:["qtc_formula"] }),
  qtc_hodges: d({ specialties:["cardiology"], problems:["prolonged_qt","ecg"], ages:["all_pediatric"], settings:["outpatient_clinic","inpatient_ward"], functions:["diagnostic_support","reference_only"], modes:["calculator"], calc:"local_active", reuse:"public_domain", inputs:["ecg"], es:["qtc hodges"], en:["hodges qtc"], compare:["qtc_formula"] }),
  bedside_schwartz: d({ specialties:renal, problems:["kidney_function","chronic_kidney_disease"], ages:["infant","toddler","preschool","school_age","adolescent"], settings:["outpatient_clinic","inpatient_ward"], functions:["diagnostic_support","longitudinal_monitoring"], modes:["calculator"], longitudinal:"primary", calc:"local_active", reuse:"open", inputs:["laboratory","growth_measurements"], es:["schwartz bedside","filtrado glomerular"], en:["bedside schwartz","pediatric egfr"], compare:["pediatric_egfr"] }),
  revised_schwartz: d({ specialties:renal, problems:["kidney_function","chronic_kidney_disease"], ages:["school_age","adolescent","age_defined_by_tool"], settings:["outpatient_clinic","inpatient_ward"], functions:["diagnostic_support","longitudinal_monitoring"], modes:["calculator"], longitudinal:"primary", calc:"local_active", reuse:"open", inputs:["laboratory","growth_measurements"], es:["schwartz revisado","ckid"], en:["revised schwartz","ckid egfr"], compare:["pediatric_egfr"] }),
  prifle: d({ specialties:[...renal,...picu], problems:["acute_kidney_injury"], ages:["all_pediatric"], settings:["picu","inpatient_ward"], functions:["organ_dysfunction","staging","longitudinal_monitoring"], modes:["calculator","longitudinal_staging"], longitudinal:"primary", calc:"local_planned", reuse:"open", risk:"critical", inputs:["laboratory","vital_signs"], es:["prifle","lesion renal aguda"], en:["prifle","pediatric aki"], compare:["pediatric_aki"] }),
  kdigo_pediatric: d({ specialties:[...renal,...picu], problems:["acute_kidney_injury"], ages:["all_pediatric"], settings:["picu","inpatient_ward"], functions:["organ_dysfunction","staging"], modes:["calculator","clinical_framework"], longitudinal:"primary", calc:"local_planned", reuse:"open", risk:"critical", inputs:["laboratory","vital_signs"], es:["kdigo pediatrico","aki"], en:["pediatric kdigo","aki"], compare:["pediatric_aki"] }),
  psofa: d({ specialties:picu, problems:["organ_dysfunction","sepsis"], ages:["all_pediatric"], settings:["picu"], functions:["organ_dysfunction","severity","prognosis"], modes:["reference_scale","longitudinal_monitoring"], longitudinal:"primary", calc:"blocked_by_evidence", reuse:"unresolved", risk:"critical", es:["psofa"], en:["psofa","pediatric sofa"], compare:["picu_organ_dysfunction"] }),
  pelod: d({ specialties:picu, problems:["organ_dysfunction"], ages:["all_pediatric"], settings:["picu","research_case_mix"], functions:["organ_dysfunction","mortality_risk"], modes:["reference_scale"], calc:"blocked_by_evidence", risk:"critical", es:["pelod"], en:["pelod"], compare:["picu_organ_dysfunction"] }),
  pelod_2: d({ specialties:picu, problems:["organ_dysfunction"], ages:["all_pediatric"], settings:["picu","research_case_mix"], functions:["organ_dysfunction","mortality_risk","longitudinal_monitoring"], modes:["calculator","reference_scale"], longitudinal:"primary", calc:"local_planned", reuse:"open", risk:"critical", inputs:["vital_signs","laboratory","blood_gas","clinical_observation"], es:["pelod-2"], en:["pelod-2"], compare:["picu_organ_dysfunction"] }),
  prism_iii: d({ specialties:picu, problems:["critical_illness"], ages:["all_pediatric"], settings:["picu","research_case_mix"], functions:["mortality_risk","prognosis"], modes:["reference_scale"], calc:"blocked_by_rights", reuse:"permission_required", risk:"critical", es:["prism iii"], en:["prism iii"], compare:["picu_mortality"] }),
  prism_iv: d({ specialties:picu, problems:["critical_illness"], ages:["all_pediatric"], settings:["picu","research_case_mix"], functions:["mortality_risk","prognosis"], modes:["calculator","reference_scale"], calc:"local_planned", reuse:"public_domain", risk:"critical", inputs:["vital_signs","laboratory","blood_gas","clinical_observation","history"], es:["prism iv"], en:["prism iv"], compare:["picu_mortality"] }),
  pim2: d({ specialties:picu, problems:["critical_illness"], ages:["all_pediatric"], settings:["picu","research_case_mix"], functions:["mortality_risk","prognosis"], modes:["reference_scale"], calc:"blocked_by_evidence", risk:"critical", es:["pim2"], en:["pim2"], compare:["picu_mortality"] }),
  pim3: d({ specialties:picu, problems:["critical_illness"], ages:["all_pediatric"], settings:["picu","research_case_mix"], functions:["mortality_risk","prognosis"], modes:["calculator","reference_scale"], calc:"local_planned", reuse:"open", risk:"critical", inputs:["vital_signs","laboratory","blood_gas","clinical_observation","history"], es:["pim3"], en:["pim3"], compare:["picu_mortality"] }),
  who_growth_module: d({ specialties:["growth_development","nutrition","general_pediatrics"], problems:["growth"], ages:["term_newborn","infant","toddler","preschool","school_age","adolescent"], settings:["primary_care","outpatient_clinic","inpatient_ward"], functions:["growth_assessment","longitudinal_monitoring"], modes:["calculator","visual_atlas"], longitudinal:"primary", calc:"local_planned", reuse:"attribution_required", inputs:["growth_measurements"], es:["oms crecimiento","percentiles oms"], en:["who growth","who child growth standards"], compare:["growth_reference"] }),
  who_growth_percentiles: d({ specialties:["growth_development","nutrition"], problems:["growth"], ages:["term_newborn","infant","toddler","preschool","school_age","adolescent"], settings:["primary_care","outpatient_clinic"], functions:["growth_assessment"], modes:["calculator"], longitudinal:"primary", calc:"local_planned", reuse:"attribution_required", inputs:["growth_measurements"], es:["percentiles oms"], en:["who growth percentiles"], compare:["growth_reference"] }),
  cdc_growth_percentiles: d({ specialties:["growth_development","nutrition"], problems:["growth"], ages:["toddler","preschool","school_age","adolescent"], exactAgeApplicability:{ minimumAgeDays:730.5, maximumAgeDaysExclusive:7305 }, settings:["primary_care","outpatient_clinic"], functions:["growth_assessment"], modes:["calculator"], longitudinal:"primary", calc:"local_planned", reuse:"public_domain", inputs:["growth_measurements"], es:["percentiles cdc"], en:["cdc 2000 growth"], compare:["growth_reference"] }),
  orbegozo_growth_percentiles: d({ specialties:["growth_development","nutrition"], problems:["growth"], ages:["all_pediatric"], settings:["primary_care","outpatient_clinic"], functions:["growth_assessment"], modes:["reference_scale"], calc:"blocked_by_rights", reuse:"permission_required", inputs:["growth_measurements"], es:["orbegozo","percentiles orbegozo"], en:["orbegozo growth"] }),
  bmi_percentile: d({ specialties:["growth_development","nutrition"], problems:["growth","body_mass_index"], ages:["toddler","preschool","school_age","adolescent"], settings:["primary_care","outpatient_clinic"], functions:["growth_assessment"], modes:["calculator"], longitudinal:"primary", calc:"local_planned", reuse:"attribution_required", inputs:["growth_measurements"], es:["percentil imc","imc"], en:["bmi percentile"], compare:["growth_reference"] }),
  head_circumference_percentile: d({ specialties:["growth_development","neurology"], problems:["growth","head_circumference"], ages:["term_newborn","infant","toddler","preschool"], settings:["primary_care","outpatient_clinic"], functions:["growth_assessment","developmental_assessment"], modes:["calculator"], longitudinal:"primary", calc:"local_planned", reuse:"attribution_required", inputs:["growth_measurements"], es:["perimetro cefalico","pc percentil"], en:["head circumference percentile"], compare:["growth_reference"] }),
  stamp: d({ specialties:["nutrition"], problems:["nutritional_risk"], ages:["all_pediatric"], settings:["inpatient_ward"], functions:["nutrition_screening"], modes:["licensed_external_tool","reference_scale"], calc:"external_official", reuse:"permission_required", es:["stamp nutricion"], en:["stamp nutrition"], compare:["nutrition_screening"] }),
  strongkids: d({ specialties:["nutrition"], problems:["nutritional_risk"], ages:["all_pediatric"], settings:["inpatient_ward"], functions:["nutrition_screening"], modes:["calculator","reference_scale"], calc:"local_planned", reuse:"open", inputs:["clinical_observation","history"], es:["strongkids"], en:["strongkids"], compare:["nutrition_screening"] }),
  pyms: d({ specialties:["nutrition"], problems:["nutritional_risk"], ages:["all_pediatric"], settings:["inpatient_ward"], functions:["nutrition_screening"], modes:["reference_scale"], calc:"blocked_by_rights", reuse:"unresolved", es:["pyms"], en:["pyms"], compare:["nutrition_screening"] }),
  flacc: d({ specialties:pain, problems:["acute_pain","postoperative_pain","nonverbal_pain"], ages:["infant","toddler","preschool","school_age"], settings:["inpatient_ward","postoperative","emergency_department"], functions:["pain_assessment"], modes:["licensed_external_tool","reference_scale"], calc:"blocked_by_rights", reuse:"permission_required", es:["flacc","dolor no verbal"], en:["flacc"], compare:["pediatric_pain"] }),
  rflacc: d({ specialties:pain, problems:["acute_pain","nonverbal_pain","developmental_disability"], ages:["all_pediatric"], settings:["inpatient_ward","postoperative"], functions:["pain_assessment"], modes:["licensed_external_tool","reference_scale"], calc:"blocked_by_rights", reuse:"permission_required", es:["r-flacc"], en:["revised flacc","rflacc"], compare:["pediatric_pain"] }),
  cheops: d({ specialties:pain, problems:["postoperative_pain","acute_pain"], ages:["toddler","preschool","school_age"], settings:["postoperative","inpatient_ward"], functions:["pain_assessment"], modes:["reference_scale"], calc:"blocked_by_rights", reuse:"unresolved", es:["cheops dolor"], en:["cheops pain"], compare:["pediatric_pain"] }),
  wong_baker_faces: d({ specialties:pain, problems:["acute_pain","self_report_pain"], ages:["preschool","school_age","adolescent"], settings:["emergency_department","outpatient_clinic","inpatient_ward"], functions:["pain_assessment"], modes:["licensed_external_tool","visual_atlas"], calc:"external_official", reuse:"external_only", inputs:["questionnaire_self_report"], es:["wong baker","caras dolor"], en:["wong-baker faces"], compare:["pediatric_pain"] }),
  visual_analogue_scale: d({ specialties:pain, problems:["acute_pain","self_report_pain"], ages:["school_age","adolescent"], settings:["emergency_department","outpatient_clinic","inpatient_ward"], functions:["pain_assessment"], modes:["calculator"], calc:"local_planned", reuse:"public_domain", inputs:["questionnaire_self_report"], es:["escala visual analogica","eva"], en:["visual analogue scale","vas"], compare:["pediatric_pain"] }),
  pediatric_cpr: d({ specialties:[...ed,...picu], problems:["cardiac_arrest","resuscitation"], ages:["infant","toddler","preschool","school_age","adolescent"], settings:["prehospital","emergency_department","picu"], functions:["reference_only"], modes:["clinical_framework","licensed_external_tool"], calc:"external_official", reuse:"external_only", risk:"critical", es:["rcp pediatrica"], en:["pediatric cpr"] }),
  neonatal_cpr: d({ specialties:[...neo,...ed], problems:["newborn_resuscitation"], ages:["term_newborn","preterm"], settings:["delivery_room"], functions:["reference_only"], modes:["clinical_framework","licensed_external_tool"], calc:"external_official", reuse:"external_only", risk:"critical", es:["reanimacion neonatal","rcp neonatal"], en:["neonatal resuscitation"] }),
  pediatric_bradycardia: d({ specialties:[...ed,"cardiology"], problems:["bradycardia","resuscitation"], ages:["all_pediatric"], settings:["emergency_department","picu"], functions:["reference_only"], modes:["clinical_framework","licensed_external_tool"], calc:"external_official", reuse:"external_only", risk:"critical", es:["bradicardia pediatrica"], en:["pediatric bradycardia"] }),
  pediatric_tachycardia: d({ specialties:[...ed,"cardiology"], problems:["tachycardia","resuscitation"], ages:["all_pediatric"], settings:["emergency_department","picu"], functions:["reference_only"], modes:["clinical_framework","licensed_external_tool"], calc:"external_official", reuse:"external_only", risk:"critical", es:["taquicardia pediatrica"], en:["pediatric tachycardia"] }),
  shockable_rhythm_algorithm: d({ specialties:[...ed,"cardiology"], problems:["cardiac_arrest","shockable_rhythm"], ages:["all_pediatric"], settings:["prehospital","emergency_department","picu"], functions:["reference_only"], modes:["clinical_framework","licensed_external_tool"], calc:"external_official", reuse:"external_only", risk:"critical", es:["ritmo desfibrilable"], en:["shockable rhythm"] }),
  non_shockable_rhythm_algorithm: d({ specialties:[...ed,"cardiology"], problems:["cardiac_arrest","non_shockable_rhythm"], ages:["all_pediatric"], settings:["prehospital","emergency_department","picu"], functions:["reference_only"], modes:["clinical_framework","licensed_external_tool"], calc:"external_official", reuse:"external_only", risk:"critical", es:["ritmo no desfibrilable"], en:["non-shockable rhythm"] }),
};

const priorityExpansionDiscoveryById: Record<string, ClinicalToolDiscoveryMetadata> = {
  capd: d({ specialties:picu, problems:["delirium"], ages:["infant","toddler","preschool","school_age","adolescent"], settings:["picu","inpatient_ward"], functions:["delirium_assessment","longitudinal_monitoring"], modes:["reference_scale","longitudinal_monitoring"], longitudinal:"primary", calc:"blocked_by_rights", reuse:"permission_required", risk:"high", inputs:["clinical_observation"], es:["capd","delirium pediatrico"], en:["capd","pediatric delirium"], compare:["pediatric_delirium"], related:["sos_pd","pcam_icu","pscam_icu"] }),
  wat_1: d({ specialties:picu, problems:["withdrawal","sedation"], ages:["infant","toddler","preschool","school_age","adolescent"], settings:["picu","inpatient_ward"], functions:["withdrawal_assessment","longitudinal_monitoring"], modes:["reference_scale","longitudinal_monitoring"], longitudinal:"primary", calc:"blocked_by_rights", reuse:"permission_required", risk:"high", inputs:["clinical_observation"], es:["wat-1","abstinencia sedacion"], en:["wat-1","sedation withdrawal"], compare:["pediatric_withdrawal"], related:["sbs"] }),
  sbs: d({ specialties:picu, problems:["sedation","agitation"], ages:["infant","toddler","preschool","school_age","adolescent"], settings:["picu"], functions:["sedation_assessment","longitudinal_monitoring"], modes:["reference_scale","longitudinal_monitoring"], longitudinal:"primary", calc:"blocked_by_rights", reuse:"permission_required", risk:"high", inputs:["clinical_observation"], es:["sbs","sedacion pediatrica"], en:["sbs","pediatric sedation"], compare:["pediatric_sedation"], related:["wat_1"] }),
  sos_pd: d({ specialties:picu, problems:["delirium"], ages:["infant","toddler","preschool","school_age","adolescent"], settings:["picu","inpatient_ward"], functions:["delirium_assessment","longitudinal_monitoring"], modes:["reference_scale","longitudinal_monitoring"], longitudinal:"primary", calc:"blocked_by_rights", reuse:"permission_required", risk:"high", inputs:["clinical_observation"], es:["sos-pd","delirium pediatrico"], en:["sos-pd","pediatric delirium"], compare:["pediatric_delirium"], related:["capd","pcam_icu","pscam_icu"] }),
  pcam_icu: d({ specialties:picu, problems:["delirium"], ages:["school_age","adolescent"], settings:["picu"], functions:["delirium_assessment"], modes:["reference_scale"], longitudinal:"primary", calc:"blocked_by_rights", reuse:"permission_required", risk:"high", inputs:["clinical_observation"], es:["pcam-icu","delirium ucip"], en:["pcam-icu","picu delirium"], compare:["pediatric_delirium"], related:["capd","pscam_icu","sos_pd"] }),
  pscam_icu: d({ specialties:picu, problems:["delirium"], ages:["infant","toddler","preschool"], settings:["picu"], functions:["delirium_assessment"], modes:["reference_scale"], longitudinal:"primary", calc:"blocked_by_rights", reuse:"permission_required", risk:"high", inputs:["clinical_observation"], es:["pscam-icu","delirium ninos pequenos"], en:["pscam-icu","young child delirium"], compare:["pediatric_delirium"], related:["capd","pcam_icu","sos_pd"] }),
  step_by_step: d({ specialties:[...ed,"infectious_disease"], problems:["fever","febrile_infant","invasive_bacterial_infection"], ages:["young_infant_0_90d"], exactAgeApplicability:{ maximumAgeDaysExclusive:91 }, settings:["emergency_department"], functions:["risk_stratification"], modes:["calculator","clinical_rule"], longitudinal:"not_applicable", calc:"local_planned", reuse:"open", risk:"critical", inputs:["clinical_observation","urinalysis","laboratory"], es:["step by step","lactante febril"], en:["step-by-step","febrile infant"], compare:["febrile_infant"], related:["pecarn_febrile_infant","yos"] }),
  pecarn_febrile_infant: d({ specialties:[...ed,"infectious_disease"], problems:["fever","febrile_infant","invasive_bacterial_infection"], ages:["young_infant_0_60d"], exactAgeApplicability:{ maximumAgeDaysExclusive:61 }, settings:["emergency_department"], functions:["risk_stratification"], modes:["calculator","clinical_rule"], longitudinal:"not_applicable", calc:"local_planned", reuse:"open", risk:"critical", inputs:["clinical_observation","urinalysis","laboratory"], es:["pecarn lactante febril","fiebre menor 60 dias"], en:["pecarn febrile infant","fever under 60 days"], compare:["febrile_infant"], related:["step_by_step","yos"] }),
  yos: d({ specialties:[...ed,"infectious_disease"], problems:["fever","febrile_infant"], ages:["infant","toddler","preschool"], settings:["emergency_department","primary_care"], functions:["severity"], modes:["calculator","reference_scale"], calc:"local_planned", reuse:"open", risk:"high", inputs:["clinical_observation"], es:["yos","escala observacion yale"], en:["yos","yale observation scale"], compare:["febrile_infant"], related:["step_by_step","pecarn_febrile_infant"] }),
  greulich_pyle: d({ specialties:["growth_development","endocrinology"], problems:["bone_age","growth"], ages:["infant","toddler","preschool","school_age","adolescent"], settings:["outpatient_clinic","specialty_clinic"], functions:["maturity_assessment"], modes:["visual_atlas","reference_scale"], longitudinal:"possible", calc:"external_official", reuse:"external_only", risk:"moderate", inputs:["imaging"], es:["greulich-pyle","edad osea"], en:["greulich-pyle","bone age"], compare:["bone_age"], related:["tw3"] }),
  tw3: d({ specialties:["growth_development","endocrinology"], problems:["bone_age","growth"], ages:["infant","toddler","preschool","school_age","adolescent"], settings:["outpatient_clinic","specialty_clinic"], functions:["maturity_assessment"], modes:["visual_atlas","reference_scale"], longitudinal:"possible", calc:"external_official", reuse:"external_only", risk:"moderate", inputs:["imaging"], es:["tw3","tanner whitehouse","edad osea"], en:["tw3","tanner-whitehouse","bone age"], compare:["bone_age"], related:["greulich_pyle"] }),
  tanner_staging: d({ specialties:["growth_development","endocrinology"], problems:["pubertal_development"], ages:["school_age","adolescent"], settings:["primary_care","outpatient_clinic","specialty_clinic"], functions:["staging","physical_examination"], modes:["reference_scale","examination_framework"], calc:"not_applicable", reuse:"open", risk:"moderate", inputs:["physical_examination"], es:["tanner","estadios puberales"], en:["tanner staging","sexual maturity rating"], compare:["pubertal_development"] }),
  braden_qd: d({ specialties:[...picu,"patient_safety"], problems:["pressure_injury_risk"], ages:["all_pediatric"], settings:["picu","inpatient_ward"], functions:["risk_stratification"], modes:["reference_scale"], longitudinal:"supported", calc:"blocked_by_rights", reuse:"permission_required", risk:"high", inputs:["clinical_observation"], es:["braden qd","lesion por presion"], en:["braden qd","pressure injury"], compare:["patient_safety"] }),
  humpty_dumpty_2: d({ specialties:["patient_safety","general_pediatrics"], problems:["fall_risk"], ages:["all_pediatric"], settings:["inpatient_ward","picu"], functions:["risk_stratification"], modes:["licensed_external_tool","reference_scale"], calc:"external_official", reuse:"external_only", risk:"high", inputs:["history","clinical_observation"], es:["humpty dumpty","riesgo caidas"], en:["humpty dumpty","fall risk"], compare:["patient_safety"] }),
  mchat_rf: d({ specialties:["developmental_pediatrics","behavioral_health"], problems:["autism_screening","developmental_screening"], ages:["toddler"], settings:["primary_care","outpatient_clinic"], functions:["screening"], modes:["licensed_external_tool","clinical_screen"], calc:"external_official", reuse:"external_only", risk:"high", inputs:["questionnaire_parent_report"], es:["m-chat-r/f","cribado autismo"], en:["m-chat-r/f","autism screening"], compare:["developmental_assessment"] })
};

const activeReference = (
  seed: Omit<Seed, "modes"> & { modes?: InteractionMode[] }
): ClinicalToolDiscoveryMetadata =>
  d({
    ...seed,
    modes: seed.modes ?? ["reference_scale"],
    calc: seed.calc ?? "blocked_by_rights",
    reuse: seed.reuse ?? "permission_required",
    risk: seed.risk ?? "high"
  });

const targetExpansionDiscoveryById: Record<string, ClinicalToolDiscoveryMetadata> = {
  hjhs_21: activeReference({ specialties:["hematology"], problems:["hemophilic_arthropathy"], ages:["school_age","adolescent"], settings:["specialty_clinic"], functions:["functional_status","longitudinal_monitoring"], modes:["licensed_external_tool","reference_scale"], longitudinal:"primary", calc:"external_official", reuse:"external_only", es:["hjhs","salud articular hemofilia"], en:["hjhs","hemophilia joint health"] }),
  garcia_alix_ners: d({ specialties:[...neo,...neuro], problems:["neonatal_encephalopathy","hypoxic_ischemic_encephalopathy"], ages:["term_newborn","neonate_0_28d"], settings:["nicu"], functions:["severity","longitudinal_monitoring"], longitudinal:"primary", modes:["calculator","reference_scale"], calc:"local_planned", reuse:"open", risk:"critical", inputs:["clinical_observation","physical_examination"], es:["garcia-alix","encefalopatia neonatal"], en:["garcia-alix","neonatal encephalopathy"], compare:["neonatal_encephalopathy"], related:["sarnat","thompson_hie"] }),
  pucai: activeReference({ specialties:["gastroenterology","inflammatory_bowel_disease"], problems:["ulcerative_colitis","inflammatory_bowel_disease"], ages:["school_age","adolescent"], settings:["outpatient_clinic","specialty_clinic"], functions:["disease_activity","longitudinal_monitoring"], modes:["calculator","longitudinal_monitoring"], longitudinal:"primary", calc:"local_active", reuse:"open", es:["pucai","colitis ulcerosa pediatrica"], en:["pucai","pediatric ulcerative colitis"], compare:["ibd_activity"], related:["pcdai"] }),
  pcdai: activeReference({ specialties:["gastroenterology","inflammatory_bowel_disease"], problems:["crohn_disease","inflammatory_bowel_disease"], ages:["school_age","adolescent"], settings:["outpatient_clinic","specialty_clinic"], functions:["disease_activity","longitudinal_monitoring"], modes:["calculator","longitudinal_monitoring"], longitudinal:"primary", calc:"local_active", reuse:"open", inputs:["history","clinical_observation","laboratory","growth_measurements"], es:["pcdai","actividad crohn pediatrico"], en:["pcdai","pediatric crohn activity"], compare:["ibd_activity"], related:["pucai"] }),
  phoenix_sepsis: activeReference({ specialties:[...ed,...picu,"infectious_disease"], problems:["sepsis","organ_dysfunction"], ages:["all_pediatric"], exactAgeApplicability:{ maximumAgeDaysExclusive:6574.5 }, settings:["emergency_department","picu"], functions:["organ_dysfunction","severity"], modes:["calculator","reference_scale","clinical_framework"], calc:"local_active", reuse:"open", risk:"critical", inputs:["vital_signs","laboratory","clinical_observation","blood_gas"], es:["phoenix","sepsis pediatrica"], en:["phoenix sepsis","pediatric sepsis"] }),
  parc: activeReference({ specialties:ed, problems:["appendicitis","abdominal_pain"], ages:["school_age","adolescent"], exactAgeApplicability:{ minimumAgeDays:1826.25, maximumAgeDaysExclusive:6939 }, settings:["emergency_department"], functions:["risk_stratification","diagnostic_support"], modes:["calculator","clinical_rule"], calc:"local_active", reuse:"open", risk:"critical", inputs:["history","laboratory","physical_examination"], es:["parc","riesgo apendicitis"], en:["parc","appendicitis risk"], compare:["appendicitis_risk"], related:["pediatric_appendicitis_score"] }),
  bacterial_meningitis_score: activeReference({ specialties:[...ed,"infectious_disease"], problems:["meningitis"], ages:["infant","toddler","preschool","school_age","adolescent"], settings:["emergency_department","inpatient_ward"], functions:["risk_stratification"], modes:["calculator","clinical_rule"], calc:"local_active", reuse:"open", risk:"critical", inputs:["laboratory","clinical_observation"], es:["bms","meningitis bacteriana"], en:["bacterial meningitis score","bms"] }),
  jumpstart: activeReference({ specialties:["disaster_medicine","emergency_medicine"], problems:["mass_casualty","triage"], ages:["all_pediatric"], settings:["mass_casualty","prehospital"], functions:["triage"], modes:["clinical_framework"], calc:"external_official", reuse:"external_only", risk:"critical", es:["jumpstart","triaje pediatrico"], en:["jumpstart","pediatric triage"], compare:["mass_casualty_triage"], related:["salt_triage"] }),
  salt_triage: activeReference({ specialties:["disaster_medicine","emergency_medicine"], problems:["mass_casualty","triage"], ages:["all_pediatric"], settings:["mass_casualty","prehospital"], functions:["triage"], modes:["clinical_framework"], calc:"external_official", reuse:"external_only", risk:"critical", es:["salt","triaje incidentes multiples victimas"], en:["salt","mass casualty triage"], compare:["mass_casualty_triage"], related:["jumpstart"] }),
  peld: activeReference({ specialties:["hepatology","transplant_medicine","gastroenterology"], problems:["liver_failure","transplant_priority"], ages:["infant","toddler","preschool","school_age","adolescent"], settings:["specialty_clinic","inpatient_ward"], functions:["prognosis","risk_stratification"], modes:["reference_scale"], calc:"external_official", reuse:"external_only", risk:"critical", inputs:["laboratory"], es:["peld","prioridad trasplante hepatico"], en:["peld","pediatric liver transplant"] }),
  ckid_u25: activeReference({ specialties:renal, problems:["kidney_function","chronic_kidney_disease"], ages:["toddler","preschool","school_age","adolescent","young_adult_transition"], settings:["outpatient_clinic","specialty_clinic"], functions:["diagnostic_support","longitudinal_monitoring"], modes:["calculator"], longitudinal:"primary", calc:"local_active", reuse:"open", inputs:["laboratory","growth_measurements"], es:["ckid u25","filtrado glomerular"], en:["ckid u25","egfr"] }),
  jadas10: activeReference({ specialties:["rheumatology"], problems:["juvenile_idiopathic_arthritis"], ages:["school_age","adolescent"], settings:["specialty_clinic"], functions:["disease_activity","longitudinal_monitoring"], modes:["reference_scale","longitudinal_monitoring"], longitudinal:"primary", es:["jadas10","artritis idiopatica juvenil"], en:["jadas10","juvenile idiopathic arthritis"], compare:["jia_activity"], related:["cjadas10"] }),
  cjadas10: activeReference({ specialties:["rheumatology"], problems:["juvenile_idiopathic_arthritis"], ages:["school_age","adolescent"], settings:["specialty_clinic"], functions:["disease_activity","longitudinal_monitoring"], modes:["reference_scale","longitudinal_monitoring"], longitudinal:"primary", es:["cjadas10","artritis idiopatica juvenil"], en:["cjadas10","juvenile idiopathic arthritis"], compare:["jia_activity"], related:["jadas10"] }),
  pvas: activeReference({ specialties:["rheumatology"], problems:["systemic_vasculitis"], ages:["school_age","adolescent"], settings:["specialty_clinic"], functions:["disease_activity","longitudinal_monitoring"], modes:["reference_scale","longitudinal_monitoring"], longitudinal:"primary", es:["pvas","vasculitis pediatrica"], en:["pvas","pediatric vasculitis"] }),
  pednihss: activeReference({ specialties:[...neuro,...ed], problems:["stroke"], ages:["infant","toddler","preschool","school_age","adolescent"], settings:["emergency_department","picu"], functions:["severity"], modes:["reference_scale"], calc:"blocked_by_rights", reuse:"unresolved", risk:"critical", inputs:["physical_examination"], es:["pednihss","ictus pediatrico"], en:["pednihss","pediatric stroke"] }),
  modified_bell_nec: activeReference({ specialties:neo, problems:["necrotizing_enterocolitis"], ages:["preterm","term_newborn","neonate_0_28d"], settings:["nicu"], functions:["staging","severity"], modes:["calculator","reference_scale","longitudinal_staging"], longitudinal:"supported", calc:"local_active", reuse:"open", risk:"critical", inputs:["clinical_observation","laboratory","imaging"], es:["bell","enterocolitis necrosante"], en:["modified bell","necrotizing enterocolitis"] }),
  snappii: activeReference({ specialties:neo, problems:["neonatal_severity"], ages:["preterm","term_newborn","neonate_0_28d"], settings:["nicu"], functions:["severity","mortality_risk"], modes:["reference_scale"], calc:"blocked_by_evidence", reuse:"unresolved", risk:"critical", inputs:["vital_signs","laboratory"], es:["snappe-ii","gravedad neonatal"], en:["snappe-ii","neonatal severity"] }),
  crib_ii: activeReference({ specialties:neo, problems:["neonatal_severity"], ages:["preterm","term_newborn"], settings:["nicu"], functions:["mortality_risk","severity"], modes:["reference_scale"], calc:"blocked_by_rights", reuse:"unresolved", risk:"critical", inputs:["vital_signs","laboratory"], es:["crib ii","prematuro"], en:["crib ii","preterm"] }),
  nsofa: activeReference({ specialties:neo, problems:["neonatal_sepsis","organ_dysfunction"], ages:["preterm","term_newborn","neonate_0_28d"], settings:["nicu"], functions:["organ_dysfunction","severity"], modes:["calculator","reference_scale"], calc:"local_active", reuse:"open", risk:"critical", inputs:["vital_signs","laboratory"], es:["nsofa","sepsis neonatal"], en:["nsofa","neonatal sepsis"] }),
  ispad_dka: activeReference({ specialties:["endocrinology","intensive_care"], problems:["diabetic_ketoacidosis"], ages:["school_age","adolescent"], settings:["emergency_department","picu"], functions:["severity"], modes:["clinical_framework","reference_scale"], calc:"external_official", reuse:"external_only", risk:"critical", inputs:["blood_gas","laboratory","vital_signs"], es:["ispad dka","cetoacidosis diabetica"], en:["ispad dka","diabetic ketoacidosis"] }),
  c_act: activeReference({ specialties:resp, problems:["asthma"], ages:["school_age"], settings:["outpatient_clinic","primary_care"], functions:["longitudinal_monitoring"], modes:["licensed_external_tool","longitudinal_monitoring"], longitudinal:"primary", calc:"external_official", reuse:"external_only", inputs:["questionnaire_self_report","questionnaire_parent_report"], es:["c-act","control asma infantil"], en:["c-act","childhood asthma control"], compare:["asthma_control"], related:["track"] }),
  track: activeReference({ specialties:resp, problems:["asthma"], ages:["toddler","preschool"], settings:["outpatient_clinic","primary_care"], functions:["longitudinal_monitoring"], modes:["licensed_external_tool","longitudinal_monitoring"], longitudinal:"primary", calc:"external_official", reuse:"external_only", inputs:["questionnaire_parent_report"], es:["track","control asma preescolar"], en:["track","preschool asthma control"], compare:["asthma_control"], related:["c_act"] }),
  asq: activeReference({ specialties:["adolescent_medicine","behavioral_health"], problems:["suicide_risk"], ages:["adolescent"], settings:["emergency_department","primary_care","outpatient_clinic"], functions:["screening"], modes:["clinical_screen","licensed_external_tool"], calc:"external_official", reuse:"external_only", risk:"critical", inputs:["questionnaire_self_report"], es:["asq","riesgo suicida"], en:["asq","suicide screen"] }),
  crafft_21: activeReference({ specialties:["adolescent_medicine","behavioral_health"], problems:["substance_use"], ages:["adolescent"], settings:["primary_care","outpatient_clinic","emergency_department"], functions:["screening"], modes:["clinical_screen","licensed_external_tool"], calc:"external_official", reuse:"external_only", inputs:["questionnaire_self_report"], es:["crafft","consumo sustancias"], en:["crafft","substance use"] }),
  phq9_adolescent: activeReference({ specialties:["adolescent_medicine","behavioral_health"], problems:["depression"], ages:["adolescent"], settings:["primary_care","outpatient_clinic"], functions:["screening"], modes:["clinical_screen","licensed_external_tool"], calc:"external_official", reuse:"external_only", inputs:["questionnaire_self_report"], es:["phq-9","depresion adolescente"], en:["phq-9","adolescent depression"] }),
  gad7_adolescent: activeReference({ specialties:["adolescent_medicine","behavioral_health"], problems:["anxiety"], ages:["adolescent"], settings:["primary_care","outpatient_clinic"], functions:["screening"], modes:["clinical_screen","licensed_external_tool"], calc:"external_official", reuse:"external_only", inputs:["questionnaire_self_report"], es:["gad-7","ansiedad adolescente"], en:["gad-7","adolescent anxiety"] }),
  scoff: activeReference({ specialties:["adolescent_medicine","behavioral_health"], problems:["eating_disorder"], ages:["adolescent"], settings:["primary_care","outpatient_clinic"], functions:["screening"], modes:["clinical_screen","licensed_external_tool"], calc:"external_official", reuse:"external_only", inputs:["questionnaire_self_report"], es:["scoff","trastorno conducta alimentaria"], en:["scoff","eating disorder"] }),
  vanderbilt: activeReference({ specialties:["developmental_pediatrics","behavioral_health"], problems:["adhd"], ages:["school_age","adolescent"], settings:["primary_care","outpatient_clinic"], functions:["screening"], modes:["licensed_external_tool","clinical_screen"], calc:"external_official", reuse:"external_only", inputs:["questionnaire_parent_report","questionnaire_clinician_report"], es:["vanderbilt","tdah"], en:["vanderbilt","adhd"] }),
  headsss: activeReference({ specialties:["adolescent_medicine","behavioral_health"], problems:["psychosocial_risk"], ages:["adolescent"], settings:["primary_care","outpatient_clinic"], functions:["psychosocial_screening"], modes:["clinical_framework"], calc:"not_applicable", reuse:"open", inputs:["history"], es:["headsss","entrevista adolescente"], en:["headsss","adolescent interview"] })
};

const reconciliationDiscoveryById: Record<string, ClinicalToolDiscoveryMetadata> = {
  comfort_b: activeReference({ specialties:[...picu,"sedation"], problems:["sedation","distress"], ages:["infant","toddler","preschool","school_age","adolescent"], settings:["picu"], functions:["sedation_assessment","longitudinal_monitoring"], modes:["reference_scale","longitudinal_monitoring"], longitudinal:"primary", calc:"blocked_by_rights", reuse:"permission_required", risk:"high", inputs:["clinical_observation","vital_signs"], es:["comfort","comfort-b","sedacion pediatrica"], en:["comfort","comfort-b","pediatric sedation"], compare:["pediatric_sedation"], related:["sbs","comfortneo"] }),
  n_pass: activeReference({ specialties:[...neo,...pain,"sedation"], problems:["neonatal_pain","neonatal_sedation","agitation"], ages:["preterm","term_newborn","neonate_0_28d"], settings:["nicu","newborn_ward"], functions:["pain_assessment","sedation_assessment","longitudinal_monitoring"], modes:["reference_scale","longitudinal_monitoring"], longitudinal:"primary", calc:"blocked_by_rights", reuse:"permission_required", risk:"high", inputs:["clinical_observation","vital_signs"], es:["n-pass","dolor agitacion sedacion neonatal"], en:["n-pass","neonatal pain agitation sedation"], compare:["neonatal_pain","neonatal_sedation"], related:["nips","pipp_r","edin","nfcs"] }),
  edin: activeReference({ specialties:[...neo,...pain], problems:["neonatal_pain","prolonged_pain"], ages:["preterm","term_newborn","neonate_0_28d"], settings:["nicu","newborn_ward"], functions:["pain_assessment","longitudinal_monitoring"], modes:["reference_scale","longitudinal_monitoring"], longitudinal:"primary", calc:"blocked_by_rights", reuse:"unresolved", risk:"high", inputs:["clinical_observation"], es:["edin","dolor neonatal prolongado","malestar neonatal"], en:["edin","prolonged neonatal pain"], compare:["neonatal_pain"], related:["nips","pipp_r","n_pass","nfcs"] }),
  nfcs: activeReference({ specialties:[...neo,...pain], problems:["neonatal_pain","procedural_pain"], ages:["preterm","term_newborn","neonate_0_28d"], settings:["nicu","newborn_ward"], functions:["pain_assessment"], modes:["visual_atlas","reference_scale"], calc:"blocked_by_rights", reuse:"unresolved", risk:"high", inputs:["clinical_observation"], es:["nfcs","sistema facial neonatal","dolor neonatal"], en:["nfcs","neonatal facial coding system"], compare:["neonatal_pain"], related:["nips","pipp_r","n_pass","edin"] }),
  cmas: activeReference({ specialties:["rheumatology"], problems:["juvenile_dermatomyositis","inflammatory_myopathy"], ages:["school_age","adolescent"], settings:["specialty_clinic","outpatient_clinic"], functions:["functional_status","longitudinal_monitoring"], modes:["reference_scale","longitudinal_monitoring"], longitudinal:"primary", calc:"blocked_by_rights", reuse:"permission_required", risk:"high", inputs:["functional_test","physical_examination"], es:["cmas","miositis infantil","dermatomiositis juvenil"], en:["cmas","childhood myositis assessment scale","juvenile dermatomyositis"], compare:["juvenile_myositis"], related:["mmt8","jdm_disease_activity_score","myositis_damage_index","pgals"] }),
  mmt8: activeReference({ specialties:["rheumatology"], problems:["juvenile_dermatomyositis","inflammatory_myopathy"], ages:["school_age","adolescent"], settings:["specialty_clinic","outpatient_clinic"], functions:["functional_status","longitudinal_monitoring","physical_examination"], modes:["examination_framework","reference_scale","longitudinal_monitoring"], longitudinal:"primary", calc:"blocked_by_rights", reuse:"permission_required", risk:"high", inputs:["physical_examination","functional_test"], es:["mmt8","prueba muscular manual","fuerza muscular"], en:["mmt8","manual muscle testing 8","muscle strength"], compare:["juvenile_myositis"], related:["cmas","jdm_disease_activity_score","myositis_damage_index"] }),
  chaq: activeReference({ specialties:["rheumatology"], problems:["juvenile_idiopathic_arthritis","juvenile_dermatomyositis"], ages:["school_age","adolescent"], settings:["specialty_clinic","outpatient_clinic"], functions:["functional_status","longitudinal_monitoring"], modes:["licensed_external_tool","reference_scale","longitudinal_monitoring"], longitudinal:"primary", calc:"external_official", reuse:"external_only", risk:"high", inputs:["questionnaire_parent_report","questionnaire_self_report"], es:["chaq","discapacidad artritis juvenil","funcion reumatologia"], en:["chaq","childhood health assessment questionnaire"], compare:["rheumatology_function"], related:["jadas10","cmas"] }),
  j4s: activeReference({ specialties:["rheumatology"], problems:["juvenile_systemic_sclerosis"], ages:["school_age","adolescent"], settings:["specialty_clinic"], functions:["severity","longitudinal_monitoring"], modes:["reference_scale","longitudinal_monitoring"], longitudinal:"primary", calc:"blocked_by_rights", reuse:"unresolved", risk:"high", inputs:["clinical_observation","physical_examination","laboratory"], es:["j4s","esclerosis sistemica juvenil"], en:["j4s","juvenile systemic sclerosis severity score"], compare:["juvenile_systemic_sclerosis"] }),
  jdm_disease_activity_score: activeReference({ specialties:["rheumatology"], problems:["juvenile_dermatomyositis","inflammatory_myopathy"], ages:["school_age","adolescent"], settings:["specialty_clinic","outpatient_clinic"], functions:["disease_activity","longitudinal_monitoring"], modes:["reference_scale","longitudinal_monitoring"], longitudinal:"primary", calc:"blocked_by_rights", reuse:"permission_required", risk:"high", inputs:["clinical_observation","physical_examination"], es:["jdm das","actividad dermatomiositis juvenil"], en:["jdm das","juvenile dermatomyositis disease activity score"], compare:["juvenile_myositis"], related:["cmas","mmt8","myositis_damage_index"] }),
  myositis_damage_index: activeReference({ specialties:["rheumatology"], problems:["juvenile_dermatomyositis","inflammatory_myopathy"], ages:["school_age","adolescent"], settings:["specialty_clinic","outpatient_clinic"], functions:["longitudinal_monitoring","staging"], modes:["reference_scale","longitudinal_monitoring"], longitudinal:"primary", calc:"blocked_by_rights", reuse:"permission_required", risk:"high", inputs:["history","clinical_observation","physical_examination"], es:["mdi","indice dano miositis"], en:["mdi","myositis damage index"], compare:["juvenile_myositis"], related:["cmas","mmt8","jdm_disease_activity_score"] }),
  pgals: activeReference({ specialties:["rheumatology","general_pediatrics"], problems:["musculoskeletal_screening"], ages:["toddler","preschool","school_age","adolescent"], settings:["primary_care","outpatient_clinic","specialty_clinic"], functions:["screening","physical_examination"], modes:["examination_framework","clinical_framework"], longitudinal:"not_applicable", calc:"not_applicable", reuse:"open", risk:"moderate", inputs:["physical_examination"], es:["pgals","exploracion musculoesqueletica pediatrica"], en:["pgals","pediatric musculoskeletal examination"], compare:["pediatric_musculoskeletal_exam"], related:["prems"] }),
  prems: activeReference({ specialties:["rheumatology"], problems:["musculoskeletal_assessment"], ages:["toddler","preschool","school_age","adolescent"], settings:["outpatient_clinic","specialty_clinic"], functions:["physical_examination","reference_only"], modes:["examination_framework","visual_atlas"], longitudinal:"not_applicable", calc:"not_applicable", reuse:"open", risk:"moderate", inputs:["physical_examination"], es:["prems","exploracion regional musculoesqueletica pediatrica"], en:["prems","pediatric regional musculoskeletal examination"], compare:["pediatric_musculoskeletal_exam"], related:["pgals"] }),
  modified_ross: activeReference({ specialties:["cardiology"], problems:["heart_failure"], ages:["infant","toddler","preschool","school_age","adolescent"], settings:["inpatient_ward","outpatient_clinic","specialty_clinic"], functions:["severity","staging","longitudinal_monitoring"], modes:["longitudinal_staging","reference_scale"], longitudinal:"primary", calc:"not_applicable", reuse:"open", risk:"high", inputs:["history","clinical_observation","physical_examination"], es:["ross modificado","insuficiencia cardiaca pediatrica"], en:["modified ross","pediatric heart failure"], compare:["pediatric_heart_failure"] }),
  pedmidas: activeReference({ specialties:[...neuro,"general_pediatrics"], problems:["migraine","headache"], ages:["school_age","adolescent"], settings:["outpatient_clinic","specialty_clinic","primary_care"], functions:["functional_status","longitudinal_monitoring"], modes:["licensed_external_tool","reference_scale","longitudinal_monitoring"], longitudinal:"primary", calc:"external_official", reuse:"external_only", risk:"high", inputs:["questionnaire_self_report","questionnaire_parent_report"], es:["pedmidas","discapacidad migrana pediatrica"], en:["pedmidas","pediatric migraine disability"], compare:["pediatric_headache"] }),
  scared: activeReference({ specialties:["behavioral_health","adolescent_medicine"], problems:["anxiety"], ages:["school_age","adolescent"], settings:["primary_care","outpatient_clinic","specialty_clinic"], functions:["screening","psychosocial_screening"], modes:["licensed_external_tool","clinical_screen"], calc:"external_official", reuse:"external_only", risk:"high", inputs:["questionnaire_self_report","questionnaire_parent_report"], es:["scared","ansiedad infantil"], en:["scared","child anxiety screen"], compare:["pediatric_anxiety"], related:["gad7_adolescent"] }),
  psc: activeReference({ specialties:["behavioral_health","general_pediatrics"], problems:["psychosocial_risk"], ages:["preschool","school_age","adolescent"], settings:["primary_care","outpatient_clinic"], functions:["screening","psychosocial_screening"], modes:["licensed_external_tool","clinical_screen"], calc:"external_official", reuse:"external_only", risk:"high", inputs:["questionnaire_parent_report","questionnaire_self_report"], es:["psc","lista sintomas pediatricos","cribado psicosocial"], en:["psc","pediatric symptom checklist"], compare:["pediatric_psychosocial_screening"] }),
  acq: activeReference({ specialties:[...resp,...ed], problems:["asthma"], ages:["age_defined_by_tool","school_age","adolescent"], settings:["outpatient_clinic","specialty_clinic","primary_care"], functions:["longitudinal_monitoring","treatment_response"], modes:["licensed_external_tool","longitudinal_monitoring","reference_scale"], longitudinal:"primary", calc:"external_official", reuse:"external_only", risk:"high", inputs:["questionnaire_self_report","clinical_observation"], es:["acq","cuestionario control asma"], en:["acq","asthma control questionnaire"], compare:["asthma_control"], related:["c_act","track"] }),
  wpcdai: activeReference({ specialties:["gastroenterology","inflammatory_bowel_disease"], problems:["crohn_disease","inflammatory_bowel_disease"], ages:["school_age","adolescent"], settings:["outpatient_clinic","specialty_clinic","inpatient_ward"], functions:["disease_activity","longitudinal_monitoring","treatment_response"], modes:["calculator","reference_scale","longitudinal_monitoring"], longitudinal:"primary", calc:"local_active", reuse:"open", risk:"high", inputs:["history","clinical_observation","laboratory","growth_measurements"], surfaceStatus:"active", es:["wpcdai","crohn pediatrico ponderado"], en:["wpcdai","weighted pediatric crohn disease activity index"], compare:["ibd_activity"], related:["pcdai","pucai"] }),
  fnass_21: activeReference({ specialties:[...neo], problems:["neonatal_withdrawal","neonatal_abstinence"], ages:["term_newborn","neonate_0_28d","infant"], settings:["newborn_ward","nicu"], functions:["withdrawal_assessment","longitudinal_monitoring"], modes:["reference_scale","longitudinal_monitoring"], longitudinal:"primary", calc:"blocked_by_rights", reuse:"unresolved", risk:"high", inputs:["clinical_observation","history","vital_signs"], es:["fnass","finnegan 21 items","abstinencia neonatal"], en:["fnass","21-item finnegan","neonatal abstinence scoring"], compare:["neonatal_withdrawal"], related:["eat_sleep_console"] })
};

const finalDispositionOverrides: Record<string, Partial<ClinicalToolDiscoveryMetadata>> = {
  thompson_hie: { surfaceStatus:"active" },
  pipp: { surfaceStatus:"blocked" },
  neonatal_growth_fenton: { surfaceStatus:"active" },
  brighton_pews: { surfaceStatus:"blocked" },
  bedside_pews: { surfaceStatus:"active" },
  risc: { surfaceStatus:"active" },
  mrisc: { surfaceStatus:"active" },
  gorelick_dehydration: { surfaceStatus:"active" },
  pediatric_burn_tbsa: { reuseStatus:"unresolved" },
  prifle: { surfaceStatus:"active" },
  pelod: { surfaceStatus:"deprecated", calculationAvailability:"not_applicable" },
  pelod_2: { surfaceStatus:"active" },
  prism_iii: { surfaceStatus:"deprecated", calculationAvailability:"not_applicable" },
  prism_iv: { surfaceStatus:"active" },
  pim2: { surfaceStatus:"deprecated", calculationAvailability:"not_applicable" },
  pim3: { surfaceStatus:"active" },
  cdc_growth_percentiles: { surfaceStatus:"active" },
  orbegozo_growth_percentiles: { surfaceStatus:"blocked" },
  stamp: { surfaceStatus:"blocked" },
  strongkids: { surfaceStatus:"active" },
  pyms: { surfaceStatus:"blocked" },
  flacc: { surfaceStatus:"blocked", calculationAvailability:"blocked_by_rights", reuseStatus:"permission_required" },
  rflacc: { surfaceStatus:"blocked" },
  cheops: { surfaceStatus:"blocked" },
  visual_analogue_scale: { surfaceStatus:"active" },
  pediatric_cpr: { surfaceStatus:"blocked", calculationAvailability:"blocked_by_rights", reuseStatus:"permission_required" },
  neonatal_cpr: { surfaceStatus:"blocked", calculationAvailability:"blocked_by_rights", reuseStatus:"permission_required" },
  pediatric_bradycardia: { surfaceStatus:"blocked", calculationAvailability:"blocked_by_rights", reuseStatus:"permission_required" },
  pediatric_tachycardia: { surfaceStatus:"blocked", calculationAvailability:"blocked_by_rights", reuseStatus:"permission_required" },
  shockable_rhythm_algorithm: { surfaceStatus:"blocked", calculationAvailability:"blocked_by_rights", reuseStatus:"permission_required" },
  non_shockable_rhythm_algorithm: { surfaceStatus:"blocked", calculationAvailability:"blocked_by_rights", reuseStatus:"permission_required" }
};

const applyFinalDisposition = (
  entries: Record<string, ClinicalToolDiscoveryMetadata>
): Record<string, ClinicalToolDiscoveryMetadata> => Object.fromEntries(
  Object.entries(entries).map(([id, metadata]) => [
    id,
    { ...metadata, ...finalDispositionOverrides[id] }
  ])
);

export const toolDiscoveryById: Record<string, ClinicalToolDiscoveryMetadata> = {
  ...applyFinalDisposition(existingToolDiscoveryById),
  ...priorityExpansionDiscoveryById,
  ...targetExpansionDiscoveryById,
  ...reconciliationDiscoveryById
};

export const getToolDiscovery = (toolId: string): ClinicalToolDiscoveryMetadata | undefined =>
  toolDiscoveryById[toolId];

export const clinicalComparisonGroups = {
  acute_asthma_severity: { id: "acute_asthma_severity" },
  asthma_control: { id: "asthma_control" },
  appendicitis_risk: { id: "appendicitis_risk" },
  bone_age: { id: "bone_age" },
  bronchiolitis_severity: { id: "bronchiolitis_severity" },
  burn_assessment: { id: "burn_assessment" },
  consciousness: { id: "consciousness" },
  croup_severity: { id: "croup_severity" },
  developmental_assessment: { id: "developmental_assessment" },
  febrile_infant: { id: "febrile_infant" },
  gestational_age_assessment: { id: "gestational_age_assessment" },
  growth_reference: { id: "growth_reference" },
  ibd_activity: { id: "ibd_activity" },
  jia_activity: { id: "jia_activity" },
  mass_casualty_triage: { id: "mass_casualty_triage" },
  neonatal_encephalopathy: { id: "neonatal_encephalopathy" },
  neonatal_hyperbilirubinemia: { id: "neonatal_hyperbilirubinemia" },
  neonatal_pain: { id: "neonatal_pain" },
  neonatal_respiratory_distress: { id: "neonatal_respiratory_distress" },
  neonatal_sedation: { id: "neonatal_sedation" },
  neonatal_withdrawal: { id: "neonatal_withdrawal" },
  nutrition_screening: { id: "nutrition_screening" },
  pediatric_aki: { id: "pediatric_aki" },
  pediatric_dehydration: { id: "pediatric_dehydration" },
  pediatric_early_warning: { id: "pediatric_early_warning" },
  pediatric_egfr: { id: "pediatric_egfr" },
  pediatric_head_injury: { id: "pediatric_head_injury" },
  pediatric_pain: { id: "pediatric_pain" },
  pediatric_delirium: { id: "pediatric_delirium" },
  pediatric_sedation: { id: "pediatric_sedation" },
  pediatric_shock: { id: "pediatric_shock" },
  pediatric_withdrawal: { id: "pediatric_withdrawal" },
  patient_safety: { id: "patient_safety" },
  picu_mortality: { id: "picu_mortality" },
  picu_organ_dysfunction: { id: "picu_organ_dysfunction" },
  preterm_growth: { id: "preterm_growth" },
  pubertal_development: { id: "pubertal_development" },
  qtc_formula: { id: "qtc_formula" },
  respiratory_mortality: { id: "respiratory_mortality" },
  juvenile_myositis: { id: "juvenile_myositis" },
  rheumatology_function: { id: "rheumatology_function" },
  juvenile_systemic_sclerosis: { id: "juvenile_systemic_sclerosis" },
  pediatric_musculoskeletal_exam: { id: "pediatric_musculoskeletal_exam" },
  pediatric_heart_failure: { id: "pediatric_heart_failure" },
  pediatric_headache: { id: "pediatric_headache" },
  pediatric_anxiety: { id: "pediatric_anxiety" },
  pediatric_psychosocial_screening: { id: "pediatric_psychosocial_screening" }
} as const;

export const discoveryValues = {
  specialties: [...new Set(Object.values(toolDiscoveryById).flatMap((item) => item.specialties))].sort(),
  clinicalProblems: [...new Set(Object.values(toolDiscoveryById).flatMap((item) => item.clinicalProblems))].sort(),
  ageGroups: [...new Set(Object.values(toolDiscoveryById).flatMap((item) => item.ageGroups))].sort(),
  careSettings: [...new Set(Object.values(toolDiscoveryById).flatMap((item) => item.careSettings))].sort(),
  clinicalFunctions: [...new Set(Object.values(toolDiscoveryById).flatMap((item) => item.clinicalFunctions))].sort(),
  interactionModes: [...new Set(Object.values(toolDiscoveryById).flatMap((item) => item.interactionModes))].sort()
};
