import type {
  AgeGroupTag,
  CareSettingTag,
  ClinicalFunctionTag,
  ClinicalRiskTier,
  ClinicalSpecialty,
  ClinicalToolDiscoveryMetadata,
  ContentReuseStatus,
  DiscoveryCalculationAvailability,
  InputModality,
  InteractionMode,
  LongitudinalUse
} from "../types.js";

type Seed = {
  specialties: ClinicalSpecialty[];
  problems: string[];
  ages: AgeGroupTag[];
  settings: CareSettingTag[];
  functions: ClinicalFunctionTag[];
  modes: InteractionMode[];
  longitudinal?: LongitudinalUse;
  inputs?: InputModality[];
  calc?: DiscoveryCalculationAvailability;
  reuse?: ContentReuseStatus;
  risk?: ClinicalRiskTier;
  es?: string[];
  en?: string[];
  compare?: string[];
  related?: string[];
};

const d = (seed: Seed): ClinicalToolDiscoveryMetadata => ({
  specialties: seed.specialties,
  clinicalProblems: seed.problems,
  ageGroups: seed.ages,
  careSettings: seed.settings,
  clinicalFunctions: seed.functions,
  interactionModes: seed.modes,
  longitudinalUse: seed.longitudinal ?? "possible",
  inputModalities: seed.inputs ?? ["clinical_observation"],
  calculationAvailability: seed.calc ?? "local_planned",
  reuseStatus: seed.reuse ?? "unresolved",
  clinicalRiskTier: seed.risk ?? "moderate",
  aliases: { es: seed.es ?? [], en: seed.en ?? [] },
  comparisonGroupIds: seed.compare ?? [],
  relatedToolIds: seed.related ?? []
});

const neo = ["neonatology"] as ClinicalSpecialty[];
const ed = ["emergency_medicine"] as ClinicalSpecialty[];
const picu = ["intensive_care"] as ClinicalSpecialty[];
const resp = ["respiratory"] as ClinicalSpecialty[];
const neuro = ["neurology"] as ClinicalSpecialty[];
const pain = ["pain_medicine"] as ClinicalSpecialty[];
const renal = ["nephrology"] as ClinicalSpecialty[];

export const toolDiscoveryById: Record<string, ClinicalToolDiscoveryMetadata> = {
  apgar: d({ specialties: neo, problems:["newborn_transition"], ages:["term_newborn","neonate_0_28d"], settings:["delivery_room"], functions:["severity","reference_only"], modes:["calculator","reference_scale"], longitudinal:"supported", risk:"high", calc:"local_active", reuse:"open", es:["apgar","test de apgar"], en:["apgar","apgar score"] }),
  combined_apgar: d({ specialties: neo, problems:["newborn_transition"], ages:["neonate_0_28d"], settings:["delivery_room","nicu"], functions:["reference_only"], modes:["reference_scale"], calc:"blocked_by_evidence", risk:"high", es:["apgar expandido","combined apgar"], en:["combined apgar","expanded apgar"] }),
  silverman_andersen: d({ specialties:[...neo,...resp], problems:["neonatal_respiratory_distress","respiratory_distress"], ages:["preterm","term_newborn","neonate_0_28d"], settings:["delivery_room","newborn_ward","nicu"], functions:["severity","longitudinal_monitoring"], modes:["calculator","reference_scale","longitudinal_monitoring"], longitudinal:"primary", calc:"local_active", reuse:"open", risk:"high", es:["silverman","silverman-andersen","dificultad respiratoria neonatal"], en:["silverman andersen","neonatal respiratory distress"], compare:["neonatal_respiratory_distress"] }),
  wood_downes_ferres: d({ specialties:resp, problems:["asthma","bronchospasm","respiratory_distress"], ages:["infant","toddler","preschool","school_age","adolescent"], settings:["emergency_department","inpatient_ward"], functions:["severity"], modes:["calculator","reference_scale"], calc:"local_active", reuse:"unresolved", risk:"high", es:["wood-downes-ferres","wood downes ferres"], en:["wood-downes-ferres"], compare:["acute_asthma_severity"] }),
  ballard: d({ specialties:[...neo,"growth_development"], problems:["gestational_age_assessment","maturity_assessment"], ages:["preterm","term_newborn","neonate_0_28d"], settings:["delivery_room","newborn_ward","nicu"], functions:["maturity_assessment","developmental_assessment"], modes:["visual_atlas","reference_scale"], longitudinal:"not_applicable", calc:"external_official", reuse:"permission_required", risk:"moderate", es:["ballard","new ballard","edad gestacional"], en:["new ballard score","gestational age assessment"], compare:["gestational_age_assessment"], related:["dubowitz"] }),
  dubowitz: d({ specialties:[...neo,"growth_development"], problems:["gestational_age_assessment","maturity_assessment"], ages:["preterm","term_newborn","neonate_0_28d"], settings:["newborn_ward","nicu"], functions:["maturity_assessment","developmental_assessment"], modes:["visual_atlas","reference_scale"], longitudinal:"not_applicable", calc:"blocked_by_rights", reuse:"permission_required", es:["dubowitz","madurez gestacional"], en:["dubowitz gestational assessment"], compare:["gestational_age_assessment"], related:["ballard"] }),
  sarnat: d({ specialties:[...neo,...neuro], problems:["neonatal_encephalopathy","hypoxic_ischemic_encephalopathy"], ages:["term_newborn","neonate_0_28d"], settings:["delivery_room","nicu"], functions:["staging","severity","longitudinal_monitoring"], modes:["longitudinal_staging","reference_scale"], longitudinal:"primary", calc:"not_applicable", reuse:"open", risk:"critical", es:["sarnat","encefalopatia neonatal","ehi"], en:["sarnat","neonatal encephalopathy","hie"], compare:["neonatal_encephalopathy"], related:["thompson_hie"] }),
  thompson_hie: d({ specialties:[...neo,...neuro], problems:["neonatal_encephalopathy","hypoxic_ischemic_encephalopathy"], ages:["term_newborn","neonate_0_28d"], settings:["nicu"], functions:["severity","longitudinal_monitoring"], modes:["calculator","reference_scale","longitudinal_monitoring"], longitudinal:"primary", calc:"local_planned", reuse:"open", risk:"critical", es:["thompson","encefalopatia hipoxico isquemica"], en:["thompson hie score","neonatal encephalopathy"], compare:["neonatal_encephalopathy"], related:["sarnat"] }),
  modified_finnegan: d({ specialties:neo, problems:["neonatal_withdrawal","neonatal_abstinence"], ages:["neonate_0_28d","infant"], settings:["newborn_ward","nicu"], functions:["withdrawal_assessment","longitudinal_monitoring"], modes:["reference_scale","longitudinal_monitoring"], longitudinal:"primary", calc:"blocked_by_evidence", reuse:"unresolved", risk:"high", es:["finnegan","abstinencia neonatal"], en:["finnegan","neonatal abstinence"], compare:["neonatal_withdrawal"] }),
  eat_sleep_console: d({ specialties:neo, problems:["neonatal_withdrawal","neonatal_abstinence"], ages:["term_newborn","neonate_0_28d","infant"], settings:["newborn_ward","nicu"], functions:["functional_status","longitudinal_monitoring"], modes:["clinical_framework"], longitudinal:"primary", calc:"not_applicable", reuse:"open", risk:"high", es:["eat sleep console","comer dormir consolar"], en:["eat sleep console","esc"], compare:["neonatal_withdrawal"] }),
  nips: d({ specialties:[...neo,...pain], problems:["neonatal_pain","acute_pain","procedural_pain"], ages:["preterm","term_newborn","neonate_0_28d"], settings:["newborn_ward","nicu","postoperative"], functions:["pain_assessment"], modes:["calculator","reference_scale"], longitudinal:"supported", calc:"local_active", reuse:"open", risk:"moderate", es:["nips","dolor neonatal"], en:["nips","neonatal infant pain scale"], compare:["neonatal_pain"] }),
  pipp: d({ specialties:[...neo,...pain], problems:["neonatal_pain","procedural_pain"], ages:["preterm","term_newborn","neonate_0_28d"], settings:["nicu"], functions:["pain_assessment"], modes:["reference_scale"], longitudinal:"supported", calc:"blocked_by_rights", reuse:"permission_required", es:["pipp"], en:["premature infant pain profile"], compare:["neonatal_pain"] }),
  pipp_r: d({ specialties:[...neo,...pain], problems:["neonatal_pain","procedural_pain"], ages:["preterm","term_newborn","neonate_0_28d"], settings:["nicu"], functions:["pain_assessment"], modes:["reference_scale","licensed_external_tool"], longitudinal:"supported", calc:"blocked_by_rights", reuse:"permission_required", es:["pipp-r","dolor prematuro"], en:["pipp-r","premature infant pain profile revised"], compare:["neonatal_pain"] }),
  cries: d({ specialties:[...neo,...pain], problems:["neonatal_pain","postoperative_pain"], ages:["neonate_0_28d"], settings:["postoperative","nicu"], functions:["pain_assessment"], modes:["reference_scale"], longitudinal:"supported", calc:"blocked_by_rights", reuse:"permission_required", es:["cries","dolor postoperatorio neonatal"], en:["cries neonatal pain"], compare:["neonatal_pain"] }),
  comfortneo: d({ specialties:[...neo,...pain,"sedation"], problems:["neonatal_pain","neonatal_sedation","distress"], ages:["preterm","term_newborn","neonate_0_28d"], settings:["nicu"], functions:["pain_assessment","sedation_assessment","longitudinal_monitoring"], modes:["reference_scale","longitudinal_monitoring"], longitudinal:"primary", calc:"blocked_by_rights", reuse:"permission_required", es:["comfortneo"], en:["comfortneo"], compare:["neonatal_pain","neonatal_sedation"] }),
  bhutani_nomogram: d({ specialties:[...neo,"gastroenterology"], problems:["hyperbilirubinemia","jaundice"], ages:["term_newborn","neonate_0_28d"], settings:["newborn_ward","outpatient_clinic"], functions:["risk_stratification","reference_only"], modes:["visual_atlas","reference_scale"], longitudinal:"possible", calc:"not_applicable", reuse:"permission_required", risk:"high", inputs:["laboratory"], es:["bhutani","nomograma bilirrubina","ictericia"], en:["bhutani nomogram","bilirubin nomogram"], compare:["neonatal_hyperbilirubinemia"] }),
  neonatal_growth_fenton: d({ specialties:[...neo,"growth_development","nutrition"], problems:["preterm_growth","growth"], ages:["preterm","term_newborn"], settings:["nicu","outpatient_clinic"], functions:["growth_assessment","longitudinal_monitoring"], modes:["calculator","visual_atlas"], longitudinal:"primary", calc:"local_planned", reuse:"attribution_required", inputs:["growth_measurements"], es:["fenton","crecimiento prematuro"], en:["fenton 2013","preterm growth"], compare:["preterm_growth"] }),
  pews: d({ specialties:[...ed,...picu,"general_pediatrics"], problems:["clinical_deterioration"], ages:["all_pediatric"], settings:["inpatient_ward","emergency_department"], functions:["risk_stratification","severity"], modes:["reference_scale"], calc:"blocked_by_evidence", risk:"high", es:["pews","alerta precoz pediatrica"], en:["pews","pediatric early warning score"], compare:["pediatric_early_warning"] }),
  brighton_pews: d({ specialties:[...ed,"general_pediatrics"], problems:["clinical_deterioration"], ages:["all_pediatric"], settings:["inpatient_ward"], functions:["risk_stratification","severity"], modes:["reference_scale"], calc:"blocked_by_rights", reuse:"permission_required", risk:"high", es:["brighton pews"], en:["brighton pews"], compare:["pediatric_early_warning"] }),
  bedside_pews: d({ specialties:[...ed,...picu,"general_pediatrics"], problems:["clinical_deterioration"], ages:["all_pediatric"], settings:["inpatient_ward","picu"], functions:["risk_stratification","severity","longitudinal_monitoring"], modes:["calculator","reference_scale","longitudinal_monitoring"], longitudinal:"primary", calc:"local_planned", reuse:"open", risk:"high", es:["bedside pews"], en:["bedside pews"], compare:["pediatric_early_warning"] }),
  westley_croup: d({ specialties:[...resp,...ed], problems:["croup","upper_airway_obstruction"], ages:["infant","toddler","preschool","school_age"], settings:["emergency_department","primary_care","inpatient_ward"], functions:["severity"], modes:["calculator","reference_scale"], calc:"local_active", reuse:"open", risk:"high", es:["westley","crup","laringitis"], en:["westley croup","croup"], compare:["croup_severity"] }),
  pram: d({ specialties:[...resp,...ed], problems:["asthma","acute_asthma"], ages:["preschool","school_age","adolescent"], settings:["emergency_department","inpatient_ward"], functions:["severity","treatment_response"], modes:["calculator","reference_scale"], longitudinal:"supported", calc:"local_active", reuse:"open", risk:"high", inputs:["clinical_observation","vital_signs","physical_examination"], es:["pram","asma aguda","crisis asmatica"], en:["pram","acute asthma"], compare:["acute_asthma_severity"], related:["pass"] }),
  rdai: d({ specialties:[...resp,...ed], problems:["bronchiolitis","wheezing"], ages:["infant","toddler"], settings:["emergency_department","inpatient_ward"], functions:["severity"], modes:["reference_scale"], calc:"blocked_by_rights", reuse:"permission_required", es:["rdai","bronquiolitis"], en:["rdai","respiratory distress assessment instrument"], compare:["bronchiolitis_severity"], related:["brosjod"] }),
  brosjod: d({ specialties:[...resp,...ed], problems:["bronchiolitis"], ages:["infant"], settings:["emergency_department","inpatient_ward"], functions:["severity","longitudinal_monitoring"], modes:["reference_scale","longitudinal_monitoring"], longitudinal:"supported", calc:"blocked_by_rights", reuse:"permission_required", es:["brosjod","bronquiolitis"], en:["brosjod bronchiolitis"], compare:["bronchiolitis_severity"], related:["rdai"] }),
  pass: d({ specialties:[...resp,...ed], problems:["asthma","acute_asthma"], ages:["toddler","preschool","school_age","adolescent"], settings:["emergency_department"], functions:["severity"], modes:["calculator","reference_scale"], calc:"local_planned", reuse:"open", risk:"high", es:["pass","asma"], en:["pediatric asthma severity score","pass"], compare:["acute_asthma_severity"], related:["pram"] }),
  risc: d({ specialties:[...resp,"infectious_disease"], problems:["lower_respiratory_infection","pneumonia"], ages:["infant","toddler"], settings:["inpatient_ward"], functions:["mortality_risk","prognosis"], modes:["calculator"], calc:"local_planned", reuse:"public_domain", risk:"high", es:["risc","infeccion respiratoria"], en:["risc respiratory index of severity"], compare:["respiratory_mortality"] }),
  mrisc: d({ specialties:[...resp,"infectious_disease"], problems:["lower_respiratory_infection","pneumonia"], ages:["infant","toddler","preschool"], settings:["inpatient_ward"], functions:["mortality_risk","prognosis"], modes:["calculator"], calc:"local_planned", reuse:"open", risk:"high", es:["mrisc"], en:["modified risc","mrisc"], compare:["respiratory_mortality"] }),
  pediatric_gcs: d({ specialties:[...neuro,...ed,...picu], problems:["coma","altered_consciousness","trauma"], ages:["all_pediatric"], settings:["emergency_department","picu","inpatient_ward"], functions:["severity","staging","longitudinal_monitoring"], modes:["reference_scale","licensed_external_tool"], longitudinal:"primary", calc:"external_official", reuse:"permission_required", risk:"critical", es:["glasgow pediatrico","gcs pediatrico"], en:["pediatric glasgow coma scale","pediatric gcs"], compare:["consciousness"] }),
  benes: d({ specialties:neuro, problems:["neurologic_assessment"], ages:["all_pediatric"], settings:["inpatient_ward"], functions:["reference_only"], modes:["reference_scale"], calc:"blocked_by_evidence", reuse:"unresolved", es:["benes"], en:["benes"] }),
  glasgow_adapted: d({ specialties:neuro, problems:["coma","altered_consciousness"], ages:["all_pediatric"], settings:["emergency_department","inpatient_ward"], functions:["reference_only"], modes:["reference_scale"], calc:"blocked_by_evidence", reuse:"unresolved", es:["glasgow adaptado"], en:["adapted glasgow"] }),
  clinical_dehydration_scale: d({ specialties:[...ed,"gastroenterology"], problems:["dehydration","gastroenteritis"], ages:["infant","toddler","preschool"], settings:["emergency_department","primary_care"], functions:["severity","risk_stratification"], modes:["calculator","reference_scale"], calc:"local_active", reuse:"open", risk:"high", es:["cds","escala deshidratacion"], en:["clinical dehydration scale","dehydration"], compare:["pediatric_dehydration"], related:["gorelick_dehydration"] }),
  pediatric_appendicitis_score: d({ specialties:ed, problems:["appendicitis","abdominal_pain"], ages:["school_age","adolescent","age_defined_by_tool"], settings:["emergency_department"], functions:["risk_stratification","diagnostic_support"], modes:["calculator","clinical_rule"], calc:"local_active", reuse:"open", risk:"high", es:["pas","score apendicitis pediatrica"], en:["pediatric appendicitis score","pas"], compare:["appendicitis_risk"] }),
  gorelick_dehydration: d({ specialties:[...ed,"gastroenterology"], problems:["dehydration","gastroenteritis"], ages:["infant","toddler","preschool"], settings:["emergency_department"], functions:["severity","risk_stratification"], modes:["calculator","reference_scale"], calc:"local_planned", reuse:"open", risk:"high", es:["gorelick","deshidratacion"], en:["gorelick dehydration"], compare:["pediatric_dehydration"], related:["clinical_dehydration_scale"] }),
  pediatric_burn_tbsa: d({ specialties:[...ed,"burns","trauma"], problems:["burns","tbsa"], ages:["all_pediatric"], settings:["emergency_department","prehospital","inpatient_ward"], functions:["severity","risk_stratification"], modes:["calculator","visual_atlas"], calc:"local_active", reuse:"open", risk:"critical", inputs:["physical_examination"], es:["lund browder","superficie corporal quemada","scq"], en:["pediatric tbsa","lund browder","burn surface area"], compare:["burn_assessment"] }),
  pecarn_tbi_under_2: d({ specialties:[...ed,"trauma"], problems:["traumatic_brain_injury","head_trauma"], ages:["infant","toddler"], settings:["emergency_department"], functions:["risk_stratification","diagnostic_support"], modes:["clinical_rule","calculator"], longitudinal:"not_applicable", calc:"local_active", reuse:"open", risk:"critical", es:["pecarn tce menor 2","tce lactante"], en:["pecarn tbi under 2","head injury"], compare:["pediatric_head_injury"], related:["pecarn_tbi_2_or_more","catch_tbi","chalice_tbi"] }),
  pecarn_tbi_2_or_more: d({ specialties:[...ed,"trauma"], problems:["traumatic_brain_injury","head_trauma"], ages:["toddler","preschool","school_age","adolescent"], settings:["emergency_department"], functions:["risk_stratification","diagnostic_support"], modes:["clinical_rule","calculator"], longitudinal:"not_applicable", calc:"local_active", reuse:"open", risk:"critical", es:["pecarn tce mayor 2","tce"], en:["pecarn tbi 2 or more","head injury"], compare:["pediatric_head_injury"], related:["pecarn_tbi_under_2","catch_tbi","chalice_tbi"] }),
  catch_tbi: d({ specialties:[...ed,"trauma"], problems:["traumatic_brain_injury","head_trauma"], ages:["all_pediatric"], settings:["emergency_department"], functions:["risk_stratification","diagnostic_support"], modes:["clinical_rule","calculator"], longitudinal:"not_applicable", calc:"local_active", reuse:"open", risk:"critical", es:["catch","tce"], en:["catch head injury"], compare:["pediatric_head_injury"] }),
  chalice_tbi: d({ specialties:[...ed,"trauma"], problems:["traumatic_brain_injury","head_trauma"], ages:["all_pediatric"], settings:["emergency_department"], functions:["risk_stratification","diagnostic_support"], modes:["clinical_rule","calculator"], longitudinal:"not_applicable", calc:"local_active", reuse:"open", risk:"critical", es:["chalice","tce"], en:["chalice head injury"], compare:["pediatric_head_injury"] }),
  sipa: d({ specialties:[...ed,"trauma"], problems:["shock","trauma"], ages:["preschool","school_age","adolescent"], settings:["emergency_department","prehospital"], functions:["risk_stratification","severity"], modes:["calculator"], longitudinal:"supported", calc:"local_active", reuse:"open", risk:"critical", inputs:["vital_signs"], es:["sipa","indice shock pediatrico"], en:["shock index pediatric adjusted","sipa"], compare:["pediatric_shock"] }),
  regional_sepsis_scores: d({ specialties:[...ed,...picu,"infectious_disease"], problems:["sepsis"], ages:["all_pediatric"], settings:["emergency_department","picu"], functions:["risk_stratification","severity"], modes:["reference_scale"], calc:"blocked_by_evidence", risk:"critical", es:["sepsis pediatrica"], en:["pediatric sepsis score"] }),
  qtc_bazett: d({ specialties:["cardiology"], problems:["prolonged_qt","ecg"], ages:["all_pediatric"], settings:["emergency_department","outpatient_clinic","inpatient_ward"], functions:["diagnostic_support"], modes:["calculator"], calc:"local_active", reuse:"public_domain", inputs:["ecg"], es:["qtc bazett","qt corregido"], en:["bazett qtc"], compare:["qtc_formula"] }),
  qtc_fridericia: d({ specialties:["cardiology"], problems:["prolonged_qt","ecg"], ages:["all_pediatric"], settings:["emergency_department","outpatient_clinic","inpatient_ward"], functions:["diagnostic_support"], modes:["calculator"], calc:"local_active", reuse:"public_domain", inputs:["ecg"], es:["qtc fridericia"], en:["fridericia qtc"], compare:["qtc_formula"] }),
  qtc_framingham: d({ specialties:["cardiology"], problems:["prolonged_qt","ecg"], ages:["all_pediatric"], settings:["outpatient_clinic","inpatient_ward"], functions:["diagnostic_support","reference_only"], modes:["calculator"], calc:"local_active", reuse:"public_domain", inputs:["ecg"], es:["qtc framingham"], en:["framingham qtc"], compare:["qtc_formula"] }),
  qtc_hodges: d({ specialties:["cardiology"], problems:["prolonged_qt","ecg"], ages:["all_pediatric"], settings:["outpatient_clinic","inpatient_ward"], functions:["diagnostic_support","reference_only"], modes:["calculator"], calc:"local_active", reuse:"public_domain", inputs:["ecg"], es:["qtc hodges"], en:["hodges qtc"], compare:["qtc_formula"] }),
  bedside_schwartz: d({ specialties:renal, problems:["kidney_function","chronic_kidney_disease"], ages:["infant","toddler","preschool","school_age","adolescent"], settings:["outpatient_clinic","inpatient_ward"], functions:["diagnostic_support","longitudinal_monitoring"], modes:["calculator"], longitudinal:"primary", calc:"local_active", reuse:"open", inputs:["laboratory","growth_measurements"], es:["schwartz bedside","filtrado glomerular"], en:["bedside schwartz","pediatric egfr"], compare:["pediatric_egfr"] }),
  revised_schwartz: d({ specialties:renal, problems:["kidney_function","chronic_kidney_disease"], ages:["school_age","adolescent","age_defined_by_tool"], settings:["outpatient_clinic","inpatient_ward"], functions:["diagnostic_support","longitudinal_monitoring"], modes:["calculator"], longitudinal:"primary", calc:"local_active", reuse:"open", inputs:["laboratory","growth_measurements"], es:["schwartz revisado","ckid"], en:["revised schwartz","ckid egfr"], compare:["pediatric_egfr"] }),
  prifle: d({ specialties:[...renal,...picu], problems:["acute_kidney_injury"], ages:["all_pediatric"], settings:["picu","inpatient_ward"], functions:["organ_dysfunction","staging","longitudinal_monitoring"], modes:["calculator","longitudinal_staging"], longitudinal:"primary", calc:"local_planned", reuse:"open", risk:"critical", inputs:["laboratory","vital_signs"], es:["prifle","lesion renal aguda"], en:["prifle","pediatric aki"], compare:["pediatric_aki"] }),
  kdigo_pediatric: d({ specialties:[...renal,...picu], problems:["acute_kidney_injury"], ages:["all_pediatric"], settings:["picu","inpatient_ward"], functions:["organ_dysfunction","staging"], modes:["reference_scale","clinical_framework"], longitudinal:"primary", calc:"blocked_by_rights", reuse:"permission_required", risk:"critical", es:["kdigo pediatrico","aki"], en:["pediatric kdigo","aki"], compare:["pediatric_aki"] }),
  psofa: d({ specialties:picu, problems:["organ_dysfunction","sepsis"], ages:["all_pediatric"], settings:["picu"], functions:["organ_dysfunction","severity","prognosis"], modes:["reference_scale","longitudinal_monitoring"], longitudinal:"primary", calc:"blocked_by_rights", reuse:"permission_required", risk:"critical", es:["psofa"], en:["psofa","pediatric sofa"], compare:["picu_organ_dysfunction"] }),
  pelod: d({ specialties:picu, problems:["organ_dysfunction"], ages:["all_pediatric"], settings:["picu","research_case_mix"], functions:["organ_dysfunction","mortality_risk"], modes:["reference_scale"], calc:"blocked_by_evidence", risk:"critical", es:["pelod"], en:["pelod"], compare:["picu_organ_dysfunction"] }),
  pelod_2: d({ specialties:picu, problems:["organ_dysfunction"], ages:["all_pediatric"], settings:["picu","research_case_mix"], functions:["organ_dysfunction","mortality_risk","longitudinal_monitoring"], modes:["calculator","reference_scale"], longitudinal:"primary", calc:"local_planned", reuse:"open", risk:"critical", es:["pelod-2"], en:["pelod-2"], compare:["picu_organ_dysfunction"] }),
  prism_iii: d({ specialties:picu, problems:["critical_illness"], ages:["all_pediatric"], settings:["picu","research_case_mix"], functions:["mortality_risk","prognosis"], modes:["reference_scale"], calc:"blocked_by_rights", reuse:"permission_required", risk:"critical", es:["prism iii"], en:["prism iii"], compare:["picu_mortality"] }),
  prism_iv: d({ specialties:picu, problems:["critical_illness"], ages:["all_pediatric"], settings:["picu","research_case_mix"], functions:["mortality_risk","prognosis"], modes:["calculator","reference_scale"], calc:"local_planned", reuse:"public_domain", risk:"critical", es:["prism iv"], en:["prism iv"], compare:["picu_mortality"] }),
  pim2: d({ specialties:picu, problems:["critical_illness"], ages:["all_pediatric"], settings:["picu","research_case_mix"], functions:["mortality_risk","prognosis"], modes:["reference_scale"], calc:"blocked_by_evidence", risk:"critical", es:["pim2"], en:["pim2"], compare:["picu_mortality"] }),
  pim3: d({ specialties:picu, problems:["critical_illness"], ages:["all_pediatric"], settings:["picu","research_case_mix"], functions:["mortality_risk","prognosis"], modes:["calculator","reference_scale"], calc:"local_planned", reuse:"open", risk:"critical", es:["pim3"], en:["pim3"], compare:["picu_mortality"] }),
  who_growth_module: d({ specialties:["growth_development","nutrition","general_pediatrics"], problems:["growth"], ages:["term_newborn","infant","toddler","preschool","school_age","adolescent"], settings:["primary_care","outpatient_clinic","inpatient_ward"], functions:["growth_assessment","longitudinal_monitoring"], modes:["calculator","visual_atlas"], longitudinal:"primary", calc:"local_active", reuse:"attribution_required", inputs:["growth_measurements"], es:["oms crecimiento","percentiles oms"], en:["who growth","who child growth standards"], compare:["growth_reference"] }),
  who_growth_percentiles: d({ specialties:["growth_development","nutrition"], problems:["growth"], ages:["term_newborn","infant","toddler","preschool","school_age","adolescent"], settings:["primary_care","outpatient_clinic"], functions:["growth_assessment"], modes:["calculator"], longitudinal:"primary", calc:"local_active", reuse:"attribution_required", inputs:["growth_measurements"], es:["percentiles oms"], en:["who growth percentiles"], compare:["growth_reference"] }),
  cdc_growth_percentiles: d({ specialties:["growth_development","nutrition"], problems:["growth"], ages:["toddler","preschool","school_age","adolescent"], settings:["primary_care","outpatient_clinic"], functions:["growth_assessment"], modes:["calculator"], longitudinal:"primary", calc:"local_planned", reuse:"public_domain", inputs:["growth_measurements"], es:["percentiles cdc"], en:["cdc 2000 growth"], compare:["growth_reference"] }),
  orbegozo_growth_percentiles: d({ specialties:["growth_development","nutrition"], problems:["growth"], ages:["all_pediatric"], settings:["primary_care","outpatient_clinic"], functions:["growth_assessment"], modes:["reference_scale"], calc:"blocked_by_rights", reuse:"permission_required", inputs:["growth_measurements"], es:["orbegozo","percentiles orbegozo"], en:["orbegozo growth"] }),
  bmi_percentile: d({ specialties:["growth_development","nutrition"], problems:["growth","body_mass_index"], ages:["toddler","preschool","school_age","adolescent"], settings:["primary_care","outpatient_clinic"], functions:["growth_assessment"], modes:["calculator"], longitudinal:"primary", calc:"local_active", reuse:"attribution_required", inputs:["growth_measurements"], es:["percentil imc","imc"], en:["bmi percentile"], compare:["growth_reference"] }),
  head_circumference_percentile: d({ specialties:["growth_development","neurology"], problems:["growth","head_circumference"], ages:["term_newborn","infant","toddler","preschool"], settings:["primary_care","outpatient_clinic"], functions:["growth_assessment","developmental_assessment"], modes:["calculator"], longitudinal:"primary", calc:"local_active", reuse:"attribution_required", inputs:["growth_measurements"], es:["perimetro cefalico","pc percentil"], en:["head circumference percentile"], compare:["growth_reference"] }),
  stamp: d({ specialties:["nutrition"], problems:["nutritional_risk"], ages:["all_pediatric"], settings:["inpatient_ward"], functions:["nutrition_screening"], modes:["licensed_external_tool","reference_scale"], calc:"external_official", reuse:"permission_required", es:["stamp nutricion"], en:["stamp nutrition"], compare:["nutrition_screening"] }),
  strongkids: d({ specialties:["nutrition"], problems:["nutritional_risk"], ages:["all_pediatric"], settings:["inpatient_ward"], functions:["nutrition_screening"], modes:["calculator","reference_scale"], calc:"local_planned", reuse:"open", es:["strongkids"], en:["strongkids"], compare:["nutrition_screening"] }),
  pyms: d({ specialties:["nutrition"], problems:["nutritional_risk"], ages:["all_pediatric"], settings:["inpatient_ward"], functions:["nutrition_screening"], modes:["reference_scale"], calc:"blocked_by_rights", reuse:"permission_required", es:["pyms"], en:["pyms"], compare:["nutrition_screening"] }),
  flacc: d({ specialties:pain, problems:["acute_pain","postoperative_pain","nonverbal_pain"], ages:["infant","toddler","preschool","school_age"], settings:["inpatient_ward","postoperative","emergency_department"], functions:["pain_assessment"], modes:["licensed_external_tool","reference_scale"], calc:"blocked_by_rights", reuse:"permission_required", es:["flacc","dolor no verbal"], en:["flacc"], compare:["pediatric_pain"] }),
  rflacc: d({ specialties:pain, problems:["acute_pain","nonverbal_pain","developmental_disability"], ages:["all_pediatric"], settings:["inpatient_ward","postoperative"], functions:["pain_assessment"], modes:["licensed_external_tool","reference_scale"], calc:"blocked_by_rights", reuse:"permission_required", es:["r-flacc"], en:["revised flacc","rflacc"], compare:["pediatric_pain"] }),
  cheops: d({ specialties:pain, problems:["postoperative_pain","acute_pain"], ages:["toddler","preschool","school_age"], settings:["postoperative","inpatient_ward"], functions:["pain_assessment"], modes:["reference_scale"], calc:"blocked_by_rights", reuse:"permission_required", es:["cheops dolor"], en:["cheops pain"], compare:["pediatric_pain"] }),
  wong_baker_faces: d({ specialties:pain, problems:["acute_pain","self_report_pain"], ages:["preschool","school_age","adolescent"], settings:["emergency_department","outpatient_clinic","inpatient_ward"], functions:["pain_assessment"], modes:["licensed_external_tool","visual_atlas"], calc:"external_official", reuse:"external_only", inputs:["questionnaire_self_report"], es:["wong baker","caras dolor"], en:["wong-baker faces"], compare:["pediatric_pain"] }),
  visual_analogue_scale: d({ specialties:pain, problems:["acute_pain","self_report_pain"], ages:["school_age","adolescent"], settings:["emergency_department","outpatient_clinic","inpatient_ward"], functions:["pain_assessment"], modes:["calculator"], calc:"local_planned", reuse:"public_domain", inputs:["questionnaire_self_report"], es:["escala visual analogica","eva"], en:["visual analogue scale","vas"], compare:["pediatric_pain"] }),
  pediatric_cpr: d({ specialties:[...ed,...picu], problems:["cardiac_arrest","resuscitation"], ages:["infant","toddler","preschool","school_age","adolescent"], settings:["prehospital","emergency_department","picu"], functions:["reference_only"], modes:["clinical_framework","licensed_external_tool"], calc:"external_official", reuse:"external_only", risk:"critical", es:["rcp pediatrica"], en:["pediatric cpr"] }),
  neonatal_cpr: d({ specialties:[...neo,...ed], problems:["newborn_resuscitation"], ages:["term_newborn","preterm"], settings:["delivery_room"], functions:["reference_only"], modes:["clinical_framework","licensed_external_tool"], calc:"external_official", reuse:"external_only", risk:"critical", es:["reanimacion neonatal","rcp neonatal"], en:["neonatal resuscitation"] }),
  pediatric_bradycardia: d({ specialties:[...ed,"cardiology"], problems:["bradycardia","resuscitation"], ages:["all_pediatric"], settings:["emergency_department","picu"], functions:["reference_only"], modes:["clinical_framework","licensed_external_tool"], calc:"external_official", reuse:"external_only", risk:"critical", es:["bradicardia pediatrica"], en:["pediatric bradycardia"] }),
  pediatric_tachycardia: d({ specialties:[...ed,"cardiology"], problems:["tachycardia","resuscitation"], ages:["all_pediatric"], settings:["emergency_department","picu"], functions:["reference_only"], modes:["clinical_framework","licensed_external_tool"], calc:"external_official", reuse:"external_only", risk:"critical", es:["taquicardia pediatrica"], en:["pediatric tachycardia"] }),
  shockable_rhythm_algorithm: d({ specialties:[...ed,"cardiology"], problems:["cardiac_arrest","shockable_rhythm"], ages:["all_pediatric"], settings:["prehospital","emergency_department","picu"], functions:["reference_only"], modes:["clinical_framework","licensed_external_tool"], calc:"external_official", reuse:"external_only", risk:"critical", es:["ritmo desfibrilable"], en:["shockable rhythm"] }),
  non_shockable_rhythm_algorithm: d({ specialties:[...ed,"cardiology"], problems:["cardiac_arrest","non_shockable_rhythm"], ages:["all_pediatric"], settings:["prehospital","emergency_department","picu"], functions:["reference_only"], modes:["clinical_framework","licensed_external_tool"], calc:"external_official", reuse:"external_only", risk:"critical", es:["ritmo no desfibrilable"], en:["non-shockable rhythm"] }),
  resuscitation_weight_dose_energy: d({ specialties:[...ed,...picu], problems:["resuscitation"], ages:["all_pediatric"], settings:["emergency_department","picu","prehospital"], functions:["reference_only"], modes:["clinical_framework"], calc:"blocked_by_evidence", reuse:"unresolved", risk:"critical", es:["dosis reanimacion","energia desfibrilacion"], en:["resuscitation dose energy"] }),
  bayley: d({ specialties:["developmental_pediatrics","growth_development"], problems:["developmental_assessment"], ages:["infant","toddler","preschool"], settings:["specialty_clinic"], functions:["developmental_assessment"], modes:["licensed_external_tool","reference_scale"], calc:"external_official", reuse:"external_only", es:["bayley"], en:["bayley scales"], compare:["developmental_assessment"] }),
  denver_ii: d({ specialties:["developmental_pediatrics","growth_development"], problems:["developmental_assessment","developmental_screening"], ages:["infant","toddler","preschool"], settings:["primary_care","specialty_clinic"], functions:["screening","developmental_assessment"], modes:["licensed_external_tool","reference_scale"], calc:"external_official", reuse:"external_only", es:["denver ii","desarrollo"], en:["denver ii developmental screening"], compare:["developmental_assessment"] }),
  mass_casualty_triage: d({ specialties:["disaster_medicine","emergency_medicine"], problems:["mass_casualty","triage"], ages:["all_pediatric"], settings:["prehospital","mass_casualty"], functions:["triage"], modes:["clinical_framework"], calc:"blocked_by_evidence", reuse:"unresolved", risk:"critical", es:["triaje imv","incidente multiples victimas"], en:["mass casualty triage","mci triage"] }),
  adolescent_depression_risk: d({ specialties:["adolescent_medicine","behavioral_health"], problems:["depression"], ages:["adolescent"], settings:["primary_care","outpatient_clinic"], functions:["psychosocial_screening","screening"], modes:["clinical_screen"], calc:"blocked_by_evidence", reuse:"unresolved", risk:"high", es:["depresion adolescente"], en:["adolescent depression"] }),
  adolescent_behavior_risk: d({ specialties:["adolescent_medicine","behavioral_health"], problems:["psychosocial_risk","risk_behavior"], ages:["adolescent"], settings:["primary_care","outpatient_clinic"], functions:["psychosocial_screening","screening"], modes:["clinical_framework"], calc:"blocked_by_evidence", reuse:"unresolved", risk:"high", es:["conductas de riesgo adolescente"], en:["adolescent risk behavior"] })
};

export const getToolDiscovery = (toolId: string): ClinicalToolDiscoveryMetadata | undefined =>
  toolDiscoveryById[toolId];

export const discoveryValues = {
  specialties: [...new Set(Object.values(toolDiscoveryById).flatMap((item) => item.specialties))].sort(),
  ageGroups: [...new Set(Object.values(toolDiscoveryById).flatMap((item) => item.ageGroups))].sort(),
  careSettings: [...new Set(Object.values(toolDiscoveryById).flatMap((item) => item.careSettings))].sort(),
  clinicalFunctions: [...new Set(Object.values(toolDiscoveryById).flatMap((item) => item.clinicalFunctions))].sort(),
  interactionModes: [...new Set(Object.values(toolDiscoveryById).flatMap((item) => item.interactionModes))].sort()
};
