import { getToolBySlug } from "@peds-core/core";
import { atlas } from "../../i18n/atlas";
import type { Language } from "../../utils/language";
import { makePath } from "../../utils/routes";
import { LearnTemplate } from "./LearnTemplate";
import { Icon } from "./Icon";
export function HomeStories({ language, navigate }: { language: Language; navigate: (path: string) => void }) {
  const t = atlas[language];
  const pram = getToolBySlug("pram");
  return <div className="atlas-stories"><div className="atlas-tools-section-header" aria-label={language === "es" ? "Herramientas clínicas" : "Clinical tools"}><span>PEDSCORE TOOLS</span><strong>{language === "es" ? "Herramientas clínicas" : "Clinical tools"}</strong></div>{(["tools", "learn", "sim", "live"] as const).map((product, index) => <section id={product} className={`atlas-story atlas-story-${product}`} key={product}>
    <div className="atlas-story-inner"><div className="atlas-story-copy"><p className="eyebrow"><span>0{index + 1}</span> PEDSCORE {product.toUpperCase()}</p><h2>{t[product][0]}</h2><p>{t[product][1]}</p><ul>{t.capabilities[index].map(item => <li key={item}><Icon name="check" />{item}</li>)}</ul>{product === "tools" ? <button className="primary-link as-button" type="button" onClick={() => navigate(makePath(language, "tools"))}>{t.explore} <Icon name="arrow" /></button> : <span className="atlas-state">{t.soon}</span>}</div>
    <div className="atlas-story-visual">{product === "tools" && pram ? <div className="atlas-tool-preview"><div className="atlas-template-header"><Icon /><div><strong>PRAM</strong><p>{pram.name[language]}</p></div><span className="atlas-state">Tools</span></div><p>{pram.description[language]}</p><div className="atlas-preview-inputs">{pram.inputs?.slice(0, 3).map(input => <div key={input.id}><span>{input.label[language]}</span><span aria-hidden="true">○ &nbsp; —</span></div>)}</div><button type="button" className="atlas-text-link" onClick={() => navigate(makePath(language, "tools", "pram"))}>{t.calculator} →</button><div className="atlas-evidence-line">{t.evidence} · {t.references}</div></div> : product === "learn" ? <LearnTemplate language={language} /> : product === "sim" ? <div className="atlas-sim-preview"><p className="atlas-specimen-label">{t.preview}</p><div className="atlas-sim-orbit"><Icon name="sim" /><span>{t.capabilities[2][0]}</span></div><div className="atlas-sim-actions">{t.capabilities[2].slice(1).map((item, i) => <div key={item}><small>0{i + 1}</small>{item}<Icon name="arrow" /></div>)}</div></div> : <div className="atlas-live-preview"><p className="atlas-specimen-label">{t.preview}</p><div className="atlas-bubble"><Icon name="live" /><span>{t.capabilities[3][0]}</span></div><div className="atlas-bubble learner"><span>{t.capabilities[3][1]}</span><Icon name="arrow" /></div><div className="atlas-conversation-feedback">{t.capabilities[3][2]}<span aria-hidden="true">•••</span></div></div>}</div></div>
  </section>)}</div>;
}
