import type { Language } from "./language";

type LabelPair = { es: string; en: string };

const labels: Record<string, LabelPair> = {
  adolescent_medicine: { es: "Medicina del adolescente", en: "Adolescent medicine" },
  behavioral_health: { es: "Salud mental y conducta", en: "Behavioral health" },
  burns: { es: "Quemaduras", en: "Burns" },
  cardiology: { es: "Cardiología", en: "Cardiology" },
  developmental_pediatrics: { es: "Pediatría del desarrollo", en: "Developmental pediatrics" },
  disaster_medicine: { es: "Medicina de catástrofes", en: "Disaster medicine" },
  emergency_medicine: { es: "Urgencias pediátricas", en: "Pediatric emergency medicine" },
  endocrinology: { es: "Endocrinología", en: "Endocrinology" },
  gastroenterology: { es: "Gastroenterología", en: "Gastroenterology" },
  general_pediatrics: { es: "Pediatría general", en: "General pediatrics" },
  growth_development: { es: "Crecimiento y desarrollo", en: "Growth and development" },
  hematology: { es: "Hematología", en: "Hematology" },
  hepatology: { es: "Hepatología", en: "Hepatology" },
  infectious_disease: { es: "Enfermedades infecciosas", en: "Infectious diseases" },
  inflammatory_bowel_disease: { es: "Enfermedad inflamatoria intestinal", en: "Inflammatory bowel disease" },
  intensive_care: { es: "Cuidados intensivos", en: "Intensive care" },
  neonatology: { es: "Neonatología", en: "Neonatology" },
  nephrology: { es: "Nefrología", en: "Nephrology" },
  neurology: { es: "Neurología", en: "Neurology" },
  nutrition: { es: "Nutrición", en: "Nutrition" },
  pain_medicine: { es: "Dolor", en: "Pain medicine" },
  patient_safety: { es: "Seguridad del paciente", en: "Patient safety" },
  respiratory: { es: "Respiratorio", en: "Respiratory" },
  rheumatology: { es: "Reumatología", en: "Rheumatology" },
  sedation: { es: "Sedación", en: "Sedation" },
  transplant_medicine: { es: "Trasplante", en: "Transplant medicine" },
  trauma: { es: "Trauma", en: "Trauma" },

  adolescent: { es: "Adolescente", en: "Adolescent" },
  age_defined_by_tool: { es: "Edad definida por la herramienta", en: "Age defined by the tool" },
  all_pediatric: { es: "Todas las edades pediátricas", en: "All pediatric ages" },
  infant: { es: "Lactante", en: "Infant" },
  neonate_0_28d: { es: "Neonato, 0–28 días", en: "Neonate, 0–28 days" },
  preschool: { es: "Preescolar", en: "Preschool" },
  preterm: { es: "Prematuro", en: "Preterm" },
  school_age: { es: "Edad escolar", en: "School age" },
  term_newborn: { es: "Recién nacido a término", en: "Term newborn" },
  toddler: { es: "1–3 años", en: "Toddler" },
  young_adult_transition: { es: "Transición a adulto joven", en: "Young-adult transition" },
  young_infant_0_60d: { es: "Lactante de 0–60 días", en: "Young infant, 0–60 days" },
  young_infant_0_90d: { es: "Lactante de 0–90 días", en: "Young infant, 0–90 days" },

  delivery_room: { es: "Paritorio", en: "Delivery room" },
  emergency_department: { es: "Urgencias", en: "Emergency department" },
  inpatient_ward: { es: "Hospitalización", en: "Inpatient ward" },
  mass_casualty: { es: "Incidente con múltiples víctimas", en: "Mass-casualty incident" },
  newborn_ward: { es: "Maternidad / neonatos", en: "Newborn ward" },
  nicu: { es: "UCIN", en: "NICU" },
  outpatient_clinic: { es: "Consulta ambulatoria", en: "Outpatient clinic" },
  picu: { es: "UCIP", en: "PICU" },
  postoperative: { es: "Postoperatorio", en: "Postoperative care" },
  prehospital: { es: "Prehospitalario", en: "Prehospital" },
  primary_care: { es: "Atención primaria", en: "Primary care" },
  research_case_mix: { es: "Investigación / casuística", en: "Research / case mix" },
  specialty_clinic: { es: "Consulta especializada", en: "Specialty clinic" },

  delirium_assessment: { es: "Valoración del delirium", en: "Delirium assessment" },
  developmental_assessment: { es: "Valoración del desarrollo", en: "Developmental assessment" },
  diagnostic_support: { es: "Apoyo diagnóstico", en: "Diagnostic support" },
  disease_activity: { es: "Actividad de enfermedad", en: "Disease activity" },
  functional_status: { es: "Estado funcional", en: "Functional status" },
  growth_assessment: { es: "Valoración del crecimiento", en: "Growth assessment" },
  longitudinal_monitoring: { es: "Seguimiento longitudinal", en: "Longitudinal monitoring" },
  maturity_assessment: { es: "Valoración de madurez", en: "Maturity assessment" },
  mortality_risk: { es: "Riesgo de mortalidad", en: "Mortality risk" },
  nutrition_screening: { es: "Cribado nutricional", en: "Nutrition screening" },
  organ_dysfunction: { es: "Disfunción orgánica", en: "Organ dysfunction" },
  pain_assessment: { es: "Valoración del dolor", en: "Pain assessment" },
  physical_examination: { es: "Exploración física", en: "Physical examination" },
  prognosis: { es: "Pronóstico", en: "Prognosis" },
  psychosocial_screening: { es: "Cribado psicosocial", en: "Psychosocial screening" },
  reference_only: { es: "Consulta / referencia", en: "Reference only" },
  risk_stratification: { es: "Estratificación de riesgo", en: "Risk stratification" },
  screening: { es: "Cribado", en: "Screening" },
  sedation_assessment: { es: "Valoración de sedación", en: "Sedation assessment" },
  severity: { es: "Gravedad", en: "Severity" },
  staging: { es: "Estadificación", en: "Staging" },
  treatment_response: { es: "Respuesta al tratamiento", en: "Treatment response" },
  triage: { es: "Triaje", en: "Triage" },
  withdrawal_assessment: { es: "Valoración de abstinencia", en: "Withdrawal assessment" },

  calculator: { es: "Calculadora", en: "Calculator" },
  clinical_framework: { es: "Marco clínico", en: "Clinical framework" },
  clinical_rule: { es: "Regla clínica", en: "Clinical rule" },
  clinical_screen: { es: "Cribado clínico", en: "Clinical screen" },
  examination_framework: { es: "Marco de exploración", en: "Examination framework" },
  licensed_external_tool: { es: "Herramienta externa", en: "External licensed tool" },
  longitudinal_staging: { es: "Estadificación longitudinal", en: "Longitudinal staging" },
  reference_scale: { es: "Escala de referencia", en: "Reference scale" },
  visual_atlas: { es: "Atlas visual", en: "Visual atlas" },

  abdominal_pain: { es: "Dolor abdominal", en: "Abdominal pain" },
  acute_asthma: { es: "Asma aguda", en: "Acute asthma" },
  acute_kidney_injury: { es: "Lesión renal aguda", en: "Acute kidney injury" },
  acute_pain: { es: "Dolor agudo", en: "Acute pain" },
  adhd: { es: "TDAH", en: "ADHD" },
  agitation: { es: "Agitación", en: "Agitation" },
  altered_consciousness: { es: "Alteración de conciencia", en: "Altered consciousness" },
  anxiety: { es: "Ansiedad", en: "Anxiety" },
  appendicitis: { es: "Apendicitis", en: "Appendicitis" },
  asthma: { es: "Asma", en: "Asthma" },
  autism_screening: { es: "Cribado de autismo", en: "Autism screening" },
  body_mass_index: { es: "Índice de masa corporal", en: "Body mass index" },
  bone_age: { es: "Edad ósea", en: "Bone age" },
  bradycardia: { es: "Bradicardia", en: "Bradycardia" },
  bronchiolitis: { es: "Bronquiolitis", en: "Bronchiolitis" },
  bronchospasm: { es: "Broncoespasmo", en: "Bronchospasm" },
  cardiac_arrest: { es: "Parada cardiorrespiratoria", en: "Cardiac arrest" },
  chronic_kidney_disease: { es: "Enfermedad renal crónica", en: "Chronic kidney disease" },
  clinical_deterioration: { es: "Deterioro clínico", en: "Clinical deterioration" },
  coma: { es: "Coma", en: "Coma" },
  critical_illness: { es: "Paciente crítico", en: "Critical illness" },
  crohn_disease: { es: "Enfermedad de Crohn", en: "Crohn disease" },
  croup: { es: "Crup", en: "Croup" },
  dehydration: { es: "Deshidratación", en: "Dehydration" },
  delirium: { es: "Delirium", en: "Delirium" },
  depression: { es: "Depresión", en: "Depression" },
  developmental_disability: { es: "Discapacidad del desarrollo", en: "Developmental disability" },
  developmental_screening: { es: "Cribado del desarrollo", en: "Developmental screening" },
  diabetic_ketoacidosis: { es: "Cetoacidosis diabética", en: "Diabetic ketoacidosis" },
  distress: { es: "Distrés", en: "Distress" },
  eating_disorder: { es: "Trastorno de la conducta alimentaria", en: "Eating disorder" },
  ecg: { es: "ECG", en: "ECG" },
  fall_risk: { es: "Riesgo de caídas", en: "Fall risk" },
  febrile_infant: { es: "Lactante febril", en: "Febrile infant" },
  fever: { es: "Fiebre", en: "Fever" },
  gastroenteritis: { es: "Gastroenteritis", en: "Gastroenteritis" },
  gestational_age_assessment: { es: "Edad gestacional", en: "Gestational age assessment" },
  growth: { es: "Crecimiento", en: "Growth" },
  head_circumference: { es: "Perímetro cefálico", en: "Head circumference" },
  head_trauma: { es: "Traumatismo craneal", en: "Head trauma" },
  hemophilic_arthropathy: { es: "Artropatía hemofílica", en: "Hemophilic arthropathy" },
  hyperbilirubinemia: { es: "Hiperbilirrubinemia", en: "Hyperbilirubinemia" },
  hypoxic_ischemic_encephalopathy: { es: "Encefalopatía hipóxico-isquémica", en: "Hypoxic-ischemic encephalopathy" },
  invasive_bacterial_infection: { es: "Infección bacteriana invasiva", en: "Invasive bacterial infection" },
  jaundice: { es: "Ictericia", en: "Jaundice" },
  juvenile_idiopathic_arthritis: { es: "Artritis idiopática juvenil", en: "Juvenile idiopathic arthritis" },
  kidney_function: { es: "Función renal", en: "Kidney function" },
  liver_failure: { es: "Insuficiencia hepática", en: "Liver failure" },
  lower_respiratory_infection: { es: "Infección respiratoria baja", en: "Lower respiratory infection" },
  meningitis: { es: "Meningitis", en: "Meningitis" },
  necrotizing_enterocolitis: { es: "Enterocolitis necrosante", en: "Necrotizing enterocolitis" },
  neonatal_abstinence: { es: "Abstinencia neonatal", en: "Neonatal abstinence" },
  neonatal_encephalopathy: { es: "Encefalopatía neonatal", en: "Neonatal encephalopathy" },
  neonatal_pain: { es: "Dolor neonatal", en: "Neonatal pain" },
  neonatal_respiratory_distress: { es: "Dificultad respiratoria neonatal", en: "Neonatal respiratory distress" },
  neonatal_sedation: { es: "Sedación neonatal", en: "Neonatal sedation" },
  neonatal_sepsis: { es: "Sepsis neonatal", en: "Neonatal sepsis" },
  neonatal_severity: { es: "Gravedad neonatal", en: "Neonatal severity" },
  neonatal_withdrawal: { es: "Síndrome de abstinencia neonatal", en: "Neonatal withdrawal" },
  neurologic_assessment: { es: "Valoración neurológica", en: "Neurologic assessment" },
  newborn_resuscitation: { es: "Reanimación neonatal", en: "Newborn resuscitation" },
  newborn_transition: { es: "Transición neonatal", en: "Newborn transition" },
  non_shockable_rhythm: { es: "Ritmo no desfibrilable", en: "Non-shockable rhythm" },
  nonverbal_pain: { es: "Dolor no verbal", en: "Nonverbal pain" },
  nutritional_risk: { es: "Riesgo nutricional", en: "Nutritional risk" },
  pneumonia: { es: "Neumonía", en: "Pneumonia" },
  postoperative_pain: { es: "Dolor postoperatorio", en: "Postoperative pain" },
  pressure_injury_risk: { es: "Riesgo de lesión por presión", en: "Pressure-injury risk" },
  preterm_growth: { es: "Crecimiento del prematuro", en: "Preterm growth" },
  procedural_pain: { es: "Dolor procedimental", en: "Procedural pain" },
  prolonged_qt: { es: "QT prolongado", en: "Prolonged QT" },
  psychosocial_risk: { es: "Riesgo psicosocial", en: "Psychosocial risk" },
  pubertal_development: { es: "Desarrollo puberal", en: "Pubertal development" },
  respiratory_distress: { es: "Dificultad respiratoria", en: "Respiratory distress" },
  resuscitation: { es: "Reanimación", en: "Resuscitation" },
  risk_behavior: { es: "Conductas de riesgo", en: "Risk behavior" },
  self_report_pain: { es: "Dolor autoinformado", en: "Self-reported pain" },
  sepsis: { es: "Sepsis", en: "Sepsis" },
  shock: { es: "Shock", en: "Shock" },
  shockable_rhythm: { es: "Ritmo desfibrilable", en: "Shockable rhythm" },
  stroke: { es: "Ictus", en: "Stroke" },
  substance_use: { es: "Consumo de sustancias", en: "Substance use" },
  suicide_risk: { es: "Riesgo de suicidio", en: "Suicide risk" },
  systemic_vasculitis: { es: "Vasculitis sistémica", en: "Systemic vasculitis" },
  tachycardia: { es: "Taquicardia", en: "Tachycardia" },
  tbsa: { es: "Superficie corporal quemada", en: "Total body surface area" },
  transplant_priority: { es: "Prioridad de trasplante", en: "Transplant priority" },
  traumatic_brain_injury: { es: "Traumatismo craneoencefálico", en: "Traumatic brain injury" },
  ulcerative_colitis: { es: "Colitis ulcerosa", en: "Ulcerative colitis" },
  upper_airway_obstruction: { es: "Obstrucción de vía aérea superior", en: "Upper-airway obstruction" },
  wheezing: { es: "Sibilancias", en: "Wheezing" },
  withdrawal: { es: "Abstinencia", en: "Withdrawal" }
};

export const discoveryLabel = (value: string, language: Language): string => {
  const known = labels[value];
  if (known) return known[language];

  const fallback = value.replaceAll("_", " ");
  return fallback.charAt(0).toUpperCase() + fallback.slice(1);
};
